antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: infer_fields_only_ctor	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAWaW5mZXJfZmllbGRzX29ubHlfY3Rvcg==	key=a2VybmVsL3Byb2JlfCMw	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: opaque_family_positivity	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAYb3BhcXVlX2ZhbWlseV9wb3NpdGl2aXR5	key=a2VybmVsL3Byb2JlfCMx	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: validate_cert_builtin_op	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAYdmFsaWRhdGVfY2VydF9idWlsdGluX29w	key=a2VybmVsL3Byb2JlfCMy	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: check_bounded_out_of_range	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAaY2hlY2tfYm91bmRlZF9vdXRfb2ZfcmFuZ2U=	key=a2VybmVsL3Byb2JlfCMz	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: infer_absurd	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAMaW5mZXJfYWJzdXJk	key=a2VybmVsL3Byb2JlfCM0	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: positivity_through_ctor	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAXcG9zaXRpdml0eV90aHJvdWdoX2N0b3I=	key=a2VybmVsL3Byb2JlfCM1	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: occurs_bare_global	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAASb2NjdXJzX2JhcmVfZ2xvYmFs	key=a2VybmVsL3Byb2JlfCM2	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: quote_value_surface	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAATcXVvdGVfdmFsdWVfc3VyZmFjZQ==	key=a2VybmVsL3Byb2JlfCM3	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: quote_foreign_vdata	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAATcXVvdGVfZm9yZWlnbl92ZGF0YQ==	key=a2VybmVsL3Byb2JlfCM4	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: cert_nontuple_call_arg	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAWY2VydF9ub250dXBsZV9jYWxsX2FyZw==	key=a2VybmVsL3Byb2JlfCM5	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: conv_bounded_crossrep	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAVY29udl9ib3VuZGVkX2Nyb3NzcmVw	key=a2VybmVsL3Byb2JlfCMxMA==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: cert_calls_nontuple_head	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAYY2VydF9jYWxsc19ub250dXBsZV9oZWFk	key=a2VybmVsL3Byb2JlfCMxMQ==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: infer_bounded_unregistered	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAaaW5mZXJfYm91bmRlZF91bnJlZ2lzdGVyZWQ=	key=a2VybmVsL3Byb2JlfCMxMg==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: serialize_special_atoms	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAXc2VyaWFsaXplX3NwZWNpYWxfYXRvbXM=	key=a2VybmVsL3Byb2JlfCMxMw==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: whnf_arity2_direct	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAASd2huZl9hcml0eTJfZGlyZWN0	key=a2VybmVsL3Byb2JlfCMxNA==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: infer_bounded_registered	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAYaW5mZXJfYm91bmRlZF9yZWdpc3RlcmVk	key=a2VybmVsL3Byb2JlfCMxNQ==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: cert_unknown_tuple_node	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAXY2VydF91bmtub3duX3R1cGxlX25vZGU=	key=a2VybmVsL3Byb2JlfCMxNg==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: eval_bounded_peel	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAARZXZhbF9ib3VuZGVkX3BlZWw=	key=a2VybmVsL3Byb2JlfCMxNw==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: positivity_alias_expansion	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAacG9zaXRpdml0eV9hbGlhc19leHBhbnNpb24=	key=a2VybmVsL3Byb2JlfCMxOA==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: sort_value_type_formers	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAXc29ydF92YWx1ZV90eXBlX2Zvcm1lcnM=	key=a2VybmVsL3Byb2JlfCMxOQ==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: conv_no_delta_value_surface	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAbY29udl9ub19kZWx0YV92YWx1ZV9zdXJmYWNl	key=a2VybmVsL3Byb2JlfCMyMA==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: apply_nonfun	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAMYXBwbHlfbm9uZnVu	key=a2VybmVsL3Byb2JlfCMyMQ==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: normalize_opts	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAObm9ybWFsaXplX29wdHM=	key=a2VybmVsL3Byb2JlfCMyMg==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: check_def_unknown	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAARY2hlY2tfZGVmX3Vua25vd24=	key=a2VybmVsL3Byb2JlfCMyMw==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: check_bounded_not_concrete	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAaY2hlY2tfYm91bmRlZF9ub3RfY29uY3JldGU=	key=a2VybmVsL3Byb2JlfCMyNA==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: eval_negative_debruijn	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAWZXZhbF9uZWdhdGl2ZV9kZWJydWlqbg==	key=a2VybmVsL3Byb2JlfCMyNQ==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: eval_bounded_no_branch	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAWZXZhbF9ib3VuZGVkX25vX2JyYW5jaA==	key=a2VybmVsL3Byb2JlfCMyNg==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: unify_rigid_value_heads	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAXdW5pZnlfcmlnaWRfdmFsdWVfaGVhZHM=	key=a2VybmVsL3Byb2JlfCMyNw==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: cert_nontuple_list_elem	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAXY2VydF9ub250dXBsZV9saXN0X2VsZW0=	key=a2VybmVsL3Byb2JlfCMyOA==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: validator_rejects_hole_body	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAbdmFsaWRhdG9yX3JlamVjdHNfaG9sZV9ib2R5	key=a2VybmVsL3Byb2JlfCMyOQ==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: check_bounded_in_range	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAWY2hlY2tfYm91bmRlZF9pbl9yYW5nZQ==	key=a2VybmVsL3Byb2JlfCMzMA==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: infer_value_type_formers	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAYaW5mZXJfdmFsdWVfdHlwZV9mb3JtZXJz	key=a2VybmVsL3Byb2JlfCMzMQ==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: serialize_value_surface	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAXc2VyaWFsaXplX3ZhbHVlX3N1cmZhY2U=	key=a2VybmVsL3Byb2JlfCMzMg==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: eval_no_branch	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAOZXZhbF9ub19icmFuY2g=	key=a2VybmVsL3Byb2JlfCMzMw==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: eval_bitwise_fold	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAARZXZhbF9iaXR3aXNlX2ZvbGQ=	key=a2VybmVsL3Byb2JlfCMzNA==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: unify_bounded_bridge	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAUdW5pZnlfYm91bmRlZF9icmlkZ2U=	key=a2VybmVsL3Byb2JlfCMzNQ==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: cert_dangling_callee	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAUY2VydF9kYW5nbGluZ19jYWxsZWU=	key=a2VybmVsL3Byb2JlfCMzNg==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: decode_unknown_symbol	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAVZGVjb2RlX3Vua25vd25fc3ltYm9s	key=a2VybmVsL3Byb2JlfCMzNw==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: check_ctor_via_infer	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAUY2hlY2tfY3Rvcl92aWFfaW5mZXI=	key=a2VybmVsL3Byb2JlfCMzOA==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: conv_atom_binary	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAQY29udl9hdG9tX2JpbmFyeQ==	key=a2VybmVsL3Byb2JlfCMzOQ==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: serialize_malformed_symbol	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAac2VyaWFsaXplX21hbGZvcm1lZF9zeW1ib2w=	key=a2VybmVsL3Byb2JlfCM0MA==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: remap_index_passthrough	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAXcmVtYXBfaW5kZXhfcGFzc3Rocm91Z2g=	key=a2VybmVsL3Byb2JlfCM0MQ==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: check_bounded_wrong_family	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAaY2hlY2tfYm91bmRlZF93cm9uZ19mYW1pbHk=	key=a2VybmVsL3Byb2JlfCM0Mg==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: eval_nondata_scrutinee	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAWZXZhbF9ub25kYXRhX3NjcnV0aW5lZQ==	key=a2VybmVsL3Byb2JlfCM0Mw==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: eval_bounded_iota	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAARZXZhbF9ib3VuZGVkX2lvdGE=	key=a2VybmVsL3Byb2JlfCM0NA==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: eval_value_literals	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAATZXZhbF92YWx1ZV9saXRlcmFscw==	key=a2VybmVsL3Byb2JlfCM0NQ==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: whnf_nested_fuel_restore	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAYd2huZl9uZXN0ZWRfZnVlbF9yZXN0b3Jl	key=a2VybmVsL3Byb2JlfCM0Ng==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: validator_warn_emit	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAATdmFsaWRhdG9yX3dhcm5fZW1pdA==	key=a2VybmVsL3Byb2JlfCM0Nw==	pieces=
antigen-record	kind=family	assay=positivity	label=positive	seed=-	note=occurs?/2 coverage (packed): 6 arrow-domain shapes	scaffold=g3QAAAAFbQAAAAVjdG9yc2wAAAACdAAAAAVtAAAACWFyZ19uYW1lc2wAAAADbQAAAANwcTBtAAAAA3BxMW0AAAADcHEyam0AAAAEbmFtZW0AAAADUEMwbQAAAApxdWFudGl0aWVzbAAAAANtAAAADHVucmVzdHJpY3RlZG0AAAAMdW5yZXN0cmljdGVkbQAAAAx1bnJlc3RyaWN0ZWRqbQAAAApyaWR4X2NvdW50YQBtAAAADHJwYXJhbV9jb3VudGEAdAAAAAVtAAAACWFyZ19uYW1lc2wAAAADbQAAAANwcTBtAAAAA3BxMW0AAAADcHEyam0AAAAEbmFtZW0AAAADUEMxbQAAAApxdWFudGl0aWVzbAAAAANtAAAADHVucmVzdHJpY3RlZG0AAAAMdW5yZXN0cmljdGVkbQAAAAx1bnJlc3RyaWN0ZWRqbQAAAApyaWR4X2NvdW50YQBtAAAADHJwYXJhbV9jb3VudGEAam0AAAAPZmFtX2luZGV4X25hbWVzam0AAAAJZmFtX2xldmVsYQBtAAAACGZhbV9uYW1lbQAAAARQZ2VubQAAAA9mYW1fcGFyYW1fbmFtZXNq	key=cG9zaXRpdml0eXxjdG9yOjA6YXJnOjAocGkgdW5yZXN0cmljdGVkIChjdG9yIFMgKGN0b3IgWikpIChkYXRhIE5hdCAoKSAoKSkpfGN0b3I6MDphcmc6MShwaSB1bnJlc3RyaWN0ZWQgKGRhdGEgRXF1aXZhbGVudCAoKGRhdGEgTmF0ICgpICgpKSkgKChjdG9yIFopIChjdG9yIFopKSkgKGludC10eXBlKSl8Y3RvcjowOmFyZzoyKHBpIHVucmVzdHJpY3RlZCAoY3RvciByZWZsZXhpdmUgKGN0b3IgWikpIChkYXRhIE5hdCAoKSAoKSkpfGN0b3I6MTphcmc6MChwaSB1bnJlc3RyaWN0ZWQgKGNhc2UgKGN0b3IgcmVmbGV4aXZlIChjdG9yIFopKSAoY3RvciBaKSAoYnJhbmNoIHJlZmxleGl2ZSAxIChjdG9yIFopKSkgKGludC10eXBlKSl8Y3RvcjoxOmFyZzoxKHBpIHVucmVzdHJpY3RlZCAoY2FzZSAoY3RvciBaKSAoY3RvciBaKSAoYnJhbmNoIFBDMCAwIChjdG9yIFopKSkgKGRhdGEgTmF0ICgpICgpKSl8Y3RvcjoxOmFyZzoyKHBpIHVucmVzdHJpY3RlZCAoYXBwIChpbnQgMCkgKGludCAwKSkgKGludC10eXBlKSkjNDg=	pieces=ctor:0:arg:0::(pi unrestricted (ctor S (ctor Z)) (data Nat () ()));;ctor:0:arg:1::(pi unrestricted (data Equivalent ((data Nat () ())) ((ctor Z) (ctor Z))) (int-type));;ctor:0:arg:2::(pi unrestricted (ctor reflexive (ctor Z)) (data Nat () ()));;ctor:1:arg:0::(pi unrestricted (case (ctor reflexive (ctor Z)) (ctor Z) (branch reflexive 1 (ctor Z))) (int-type));;ctor:1:arg:1::(pi unrestricted (case (ctor Z) (ctor Z) (branch PC0 0 (ctor Z))) (data Nat () ()));;ctor:1:arg:2::(pi unrestricted (app (int 0) (int 0)) (int-type))
antigen-record	kind=def_group	assay=totality/diverging	label=diverging	seed=-	note=self-call arg is a projection → arg_relation :unknown	scaffold=g3QAAAACbQAAAAVmb2N1c2wAAAABbQAAAAFoam0AAAAFbmFtZXNsAAAAAW0AAAABaGo=	key=dG90YWxpdHkvZGl2ZXJnaW5nfHR5cGU6aChwaSB1bnJlc3RyaWN0ZWQgKGRhdGEgTmF0ICgpICgpKSAoZGF0YSBOYXQgKCkgKCkpKXxib2R5OmgobGFtIHVucmVzdHJpY3RlZCAoZGF0YSBOYXQgKCkgKCkpIChjYXNlICh2YXIgMCkgKGxhbSB1bnJlc3RyaWN0ZWQgKGRhdGEgTmF0ICgpICgpKSAoZGF0YSBOYXQgKCkgKCkpKSAoYnJhbmNoIFogMCAoY3RvciBaKSkgKGJyYW5jaCBTIDEgKGFwcCAoZ2xvYmFsIGgpIChjYXNlIChjdG9yIG1rX3BhaXIgKHZhciAxKSAodmFyIDEpKSAobGFtIHVucmVzdHJpY3RlZCAoZGF0YSBTaWdtYSAoKGRhdGEgTmF0ICgpICgpKSAobGFtIHVucmVzdHJpY3RlZCAoZGF0YSBOYXQgKCkgKCkpIChkYXRhIE5hdCAoKSAoKSkpKSAoKSkgKGRhdGEgTmF0ICgpICgpKSkgKGJyYW5jaCBta19wYWlyIDIgKHZhciAxKSkpKSkpKSM0OQ==	pieces=type:h::(pi unrestricted (data Nat () ()) (data Nat () ()));;body:h::(lam unrestricted (data Nat () ()) (case (var 0) (lam unrestricted (data Nat () ()) (data Nat () ())) (branch Z 0 (ctor Z)) (branch S 1 (app (global h) (case (ctor mk_pair (var 1) (var 1)) (lam unrestricted (data Sigma ((data Nat () ()) (lam unrestricted (data Nat () ()) (data Nat () ()))) ()) (data Nat () ())) (branch mk_pair 2 (var 1)))))))
antigen-record	kind=def_group	assay=totality/terminating	label=terminating	seed=-	note=structural recursion with a rich call-free base branch	scaffold=g3QAAAACbQAAAAVmb2N1c2wAAAABbQAAAAFoam0AAAAFbmFtZXNsAAAAAW0AAAABaGo=	key=dG90YWxpdHkvdGVybWluYXRpbmd8dHlwZTpoKHBpIHVucmVzdHJpY3RlZCAoZGF0YSBOYXQgKCkgKCkpIChkYXRhIE5hdCAoKSAoKSkpfGJvZHk6aChsYW0gdW5yZXN0cmljdGVkIChkYXRhIE5hdCAoKSAoKSkgKGNhc2UgKHZhciAwKSAobGFtIHVucmVzdHJpY3RlZCAoZGF0YSBOYXQgKCkgKCkpIChkYXRhIE5hdCAoKSAoKSkpIChicmFuY2ggWiAwIChjdG9yIG1rX3BhaXIgKGNhc2UgKHZhciAwKSAobGFtIHVucmVzdHJpY3RlZCAoZGF0YSBTaWdtYSAoKGRhdGEgTmF0ICgpICgpKSAobGFtIHVucmVzdHJpY3RlZCAoZGF0YSBOYXQgKCkgKCkpIChkYXRhIE5hdCAoKSAoKSkpKSAoKSkgKGRhdGEgTmF0ICgpICgpKSkgKGJyYW5jaCBta19wYWlyIDIgKHZhciAxKSkpIChjdG9yIG1rX3BhaXIgKGNhc2UgKHZhciAwKSAobGFtIHVucmVzdHJpY3RlZCAoZGF0YSBTaWdtYSAoKGRhdGEgTmF0ICgpICgpKSAobGFtIHVucmVzdHJpY3RlZCAoZGF0YSBOYXQgKCkgKCkpIChkYXRhIE5hdCAoKSAoKSkpKSAoKSkgKGRhdGEgTmF0ICgpICgpKSkgKGJyYW5jaCBta19wYWlyIDIgKHZhciAwKSkpIChjdG9yIG1rX3BhaXIgKGRhdGEgRXF1aXZhbGVudCAoKHZhciAwKSkgKCh2YXIgMCkgKHZhciAwKSkpIChjdG9yIG1rX3BhaXIgKGN0b3IgcmVmbGV4aXZlICh2YXIgMCkpIChjdG9yIG1rX3BhaXIgKGFwcCAoY2FzZSAoY3RvciByZWZsZXhpdmUgKHZhciAwKSkgKGxhbSB1bnJlc3RyaWN0ZWQgKGRhdGEgTmF0ICgpICgpKSAodmFyIDApKSAoYnJhbmNoIHJlZmxleGl2ZSAxIChsYW0gdW5yZXN0cmljdGVkIChkYXRhIE5hdCAoKSAoKSkgKHZhciAwKSkpKSAodmFyIDApKSAoY3RvciBta19wYWlyIChwaSB1bnJlc3RyaWN0ZWQgKGRhdGEgTmF0ICgpICgpKSAoZGF0YSBOYXQgKCkgKCkpKSAoY3RvciBta19wYWlyIChkYXRhIFNpZ21hICgoZGF0YSBOYXQgKCkgKCkpIChsYW0gdW5yZXN0cmljdGVkIChkYXRhIE5hdCAoKSAoKSkgKGRhdGEgTmF0ICgpICgpKSkpICgpKSAoYXBwICh2YXIgMCkgKHZhciAwKSkpKSkpKSkpKSAoYnJhbmNoIFMgMSAoYXBwIChnbG9iYWwgaCkgKHZhciAwKSkpKSkjNTA=	pieces=type:h::(pi unrestricted (data Nat () ()) (data Nat () ()));;body:h::(lam unrestricted (data Nat () ()) (case (var 0) (lam unrestricted (data Nat () ()) (data Nat () ())) (branch Z 0 (ctor mk_pair (case (var 0) (lam unrestricted (data Sigma ((data Nat () ()) (lam unrestricted (data Nat () ()) (data Nat () ()))) ()) (data Nat () ())) (branch mk_pair 2 (var 1))) (ctor mk_pair (case (var 0) (lam unrestricted (data Sigma ((data Nat () ()) (lam unrestricted (data Nat () ()) (data Nat () ()))) ()) (data Nat () ())) (branch mk_pair 2 (var 0))) (ctor mk_pair (data Equivalent ((var 0)) ((var 0) (var 0))) (ctor mk_pair (ctor reflexive (var 0)) (ctor mk_pair (app (case (ctor reflexive (var 0)) (lam unrestricted (data Nat () ()) (var 0)) (branch reflexive 1 (lam unrestricted (data Nat () ()) (var 0)))) (var 0)) (ctor mk_pair (pi unrestricted (data Nat () ()) (data Nat () ())) (ctor mk_pair (data Sigma ((data Nat () ()) (lam unrestricted (data Nat () ()) (data Nat () ()))) ()) (app (var 0) (var 0)))))))))) (branch S 1 (app (global h) (var 0)))))
antigen-record	kind=def_group	assay=totality/diverging	label=diverging	seed=-	note=nullary mutual loop f = g, g = f (0×0 cross-function edges)	scaffold=g3QAAAACbQAAAAVmb2N1c2wAAAACbQAAAAFmbQAAAAFnam0AAAAFbmFtZXNsAAAAAm0AAAABZm0AAAABZ2o=	key=dG90YWxpdHkvZGl2ZXJnaW5nfHR5cGU6ZihkYXRhIE5hdCAoKSAoKSl8Ym9keTpmKGdsb2JhbCBnKXx0eXBlOmcoZGF0YSBOYXQgKCkgKCkpfGJvZHk6ZyhnbG9iYWwgZikjNTE=	pieces=type:f::(data Nat () ());;body:f::(global g);;type:g::(data Nat () ());;body:g::(global f)
antigen-record	kind=branch_unify	assay=branchunify/verdict	label=impossible	seed=-	note=Nl nat_lit!=nat_lit fast path (unify_one 1003, distinct)	scaffold=g3QAAAAEbQAAAAVjbmFtZW0AAAADbmxjbQAAAAhjdHhfdmFyc2EAbQAAAAVkbmFtZW0AAAACTmxtAAAAC3BhcmFtX2NvdW50YQA=	key=YnJhbmNodW5pZnkvdmVyZGljdHxpZHg6MChuYXQgMykjNTI=	pieces=idx:0::(nat 3)
antigen-record	kind=branch_unify	assay=branchunify/verdict	label=impossible	seed=-	note=Foo MkFoo vs rigid Z index — genuine S/Z clash (S9 control)	scaffold=g3QAAAAEbQAAAAVjbmFtZW0AAAAFTWtGb29tAAAACGN0eF92YXJzYQJtAAAABWRuYW1lbQAAAANGb29tAAAAC3BhcmFtX2NvdW50YQE=	key=YnJhbmNodW5pZnkvdmVyZGljdHxpZHg6MChjdG9yIFopfHBhcmFtOjAodmFyIDEpIzUz	pieces=idx:0::(ctor Z);;param:0::(var 1)
antigen-record	kind=branch_unify	assay=branchunify/verdict	label=trivial	seed=-	note=SpineU stuck plus-application spine element — unify_spine :undecided drop (1047)	scaffold=g3QAAAAEbQAAAAVjbmFtZW0AAAADc3B1bQAAAAhjdHhfdmFyc2EAbQAAAAVkbmFtZW0AAAAGU3BpbmVVbQAAAAtwYXJhbV9jb3VudGEA	key=YnJhbmNodW5pZnkvdmVyZGljdHxpZHg6MChjdG9yIFMgKGN0b3IgWikpIzU0	pieces=idx:0::(ctor S (ctor Z))
antigen-record	kind=branch_unify	assay=branchunify/verdict	label=solved	seed=-	note=Sq mksq [var0,var1] — forced equation (Solution step)	scaffold=g3QAAAAEbQAAAAVjbmFtZW0AAAAEbWtzcW0AAAAIY3R4X3ZhcnNhAm0AAAAFZG5hbWVtAAAAAlNxbQAAAAtwYXJhbV9jb3VudGEA	key=YnJhbmNodW5pZnkvdmVyZGljdHxpZHg6MCh2YXIgMCl8aWR4OjEodmFyIDEpIzU1	pieces=idx:0::(var 0);;idx:1::(var 1)
antigen-record	kind=branch_unify	assay=branchunify/verdict	label=solved	seed=-	note=Foo MkFoo over a free index — param in result-index spine is SOLVABLE (S9)	scaffold=g3QAAAAEbQAAAAVjbmFtZW0AAAAFTWtGb29tAAAACGN0eF92YXJzYQJtAAAABWRuYW1lbQAAAANGb29tAAAAC3BhcmFtX2NvdW50YQE=	key=YnJhbmNodW5pZnkvdmVyZGljdHxpZHg6MCh2YXIgMCl8cGFyYW06MCh2YXIgMSkjNTY=	pieces=idx:0::(var 0);;param:0::(var 1)
antigen-record	kind=branch_unify	assay=branchunify/verdict	label=impossible	seed=-	note=Ty tnat [Type0] — rigid data/Type clash	scaffold=g3QAAAAEbQAAAAVjbmFtZW0AAAAEdG5hdG0AAAAIY3R4X3ZhcnNhAG0AAAAFZG5hbWVtAAAAAlR5bQAAAAtwYXJhbV9jb3VudGEA	key=YnJhbmNodW5pZnkvdmVyZGljdHxpZHg6MCh0eXBlIDApIzU3	pieces=idx:0::(type 0)
antigen-record	kind=branch_unify	assay=branchunify/verdict	label=trivial	seed=-	note=Nl nat_lit result index vs ctor-tower scrutinee — peel nat_lit->ctor (unify_one 1005/1006)	scaffold=g3QAAAAEbQAAAAVjbmFtZW0AAAADbmxjbQAAAAhjdHhfdmFyc2EAbQAAAAVkbmFtZW0AAAACTmxtAAAAC3BhcmFtX2NvdW50YQA=	key=YnJhbmNodW5pZnkvdmVyZGljdHxpZHg6MChjdG9yIFMgKGN0b3IgUyAoY3RvciBaKSkpIzU4	pieces=idx:0::(ctor S (ctor S (ctor Z)))
antigen-record	kind=branch_unify	assay=branchunify/verdict	label=bad_motive	seed=-	note=motive = an opaque outer variable — apply_motive_checked's :vneutral arm keeps applying (kernel.ex:634); the motive never becomes a well-typed Pi, so infer still rejects with :bad_motive	scaffold=g3QAAAABbQAAAAxtb3RpdmVfcHJvYmVtAAAAB25ldXRyYWw=	key=YnJhbmNodW5pZnkvdmVyZGljdHwjNTk=	pieces=
antigen-record	kind=branch_unify	assay=branchunify/verdict	label=solved	seed=-	note=Cyc4b interleaved crossing — union-find self-loop collapse (bind_index 1073)	scaffold=g3QAAAAEbQAAAAVjbmFtZW0AAAAGbWtjeWMybQAAAAhjdHhfdmFyc2ECbQAAAAVkbmFtZW0AAAAFQ3ljNGJtAAAAC3BhcmFtX2NvdW50YQA=	key=YnJhbmNodW5pZnkvdmVyZGljdHxpZHg6MCh2YXIgMCl8aWR4OjEodmFyIDEpfGlkeDoyKHZhciAxKXxpZHg6Myh2YXIgMCkjNjA=	pieces=idx:0::(var 0);;idx:1::(var 1);;idx:2::(var 1);;idx:3::(var 0)
antigen-record	kind=branch_unify	assay=branchunify/verdict	label=bad_motive	seed=-	note=motive = a concrete non-function value (a Nat type-value) — apply_motive_checked halts on the very first application, its catch-all arm (kernel.ex:635)	scaffold=g3QAAAABbQAAAAxtb3RpdmVfcHJvYmVtAAAABm5vbmZ1bg==	key=YnJhbmNodW5pZnkvdmVyZGljdHwjNjE=	pieces=
antigen-record	kind=branch_unify	assay=branchunify/verdict	label=impossible	seed=-	note=Cyc1 self-cycle — param buries into own successor, occurs-check (var_cycle? 1028/1038)	scaffold=g3QAAAAEbQAAAAVjbmFtZW0AAAAFaWRjeWNtAAAACGN0eF92YXJzYQFtAAAABWRuYW1lbQAAAARDeWMxbQAAAAtwYXJhbV9jb3VudGEB	key=YnJhbmNodW5pZnkvdmVyZGljdHxpZHg6MChjdG9yIFMgKHZhciAwKSl8cGFyYW06MCh2YXIgMCkjNjI=	pieces=idx:0::(ctor S (var 0));;param:0::(var 0)
antigen-record	kind=branch_unify	assay=branchunify/verdict	label=trivial	seed=-	note=CaseIdx :case-headed result index — subst_params :case recursion (960/961)	scaffold=g3QAAAAEbQAAAAVjbmFtZW0AAAAEbWtjaW0AAAAIY3R4X3ZhcnNhAG0AAAAFZG5hbWVtAAAAB0Nhc2VJZHhtAAAAC3BhcmFtX2NvdW50YQA=	key=YnJhbmNodW5pZnkvdmVyZGljdHxpZHg6MChjdG9yIFopIzYz	pieces=idx:0::(ctor Z)
antigen-record	kind=branch_unify	assay=branchunify/verdict	label=trivial	seed=-	note=Nl ctor-tower result index vs nat_lit scrutinee — peel ctor->nat_lit (unify_one 1008/1009)	scaffold=g3QAAAAEbQAAAAVjbmFtZW0AAAADbmx0bQAAAAhjdHhfdmFyc2EAbQAAAAVkbmFtZW0AAAACTmxtAAAAC3BhcmFtX2NvdW50YQA=	key=YnJhbmNodW5pZnkvdmVyZGljdHxpZHg6MChuYXQgMSkjNjQ=	pieces=idx:0::(nat 1)
antigen-record	kind=malformed	assay=term/rejection	label=ill_typed	seed=-	note=malformed (must reject): transport body ill-typed (Nat motive, Bd body)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9yZWplY3Rpb258dGVybShhcHAgKGNhc2UgKGN0b3IgcmVmbGV4aXZlIChkYXRhIE5hdCAoKSAoKSkgKGN0b3IgWikpIChsYW0gdW5yZXN0cmljdGVkIChkYXRhIE5hdCAoKSAoKSkgKGxhbSB1bnJlc3RyaWN0ZWQgKGRhdGEgTmF0ICgpICgpKSAobGFtIHVucmVzdHJpY3RlZCAoZGF0YSBFcXVpdmFsZW50ICgoZGF0YSBOYXQgKCkgKCkpKSAoKHZhciAxKSAodmFyIDApKSkgKHBpIHVucmVzdHJpY3RlZCAoYXBwIChsYW0gdW5yZXN0cmljdGVkIChkYXRhIE5hdCAoKSAoKSkgKGRhdGEgTmF0ICgpICgpKSkgKHZhciAyKSkgKGFwcCAobGFtIHVucmVzdHJpY3RlZCAoZGF0YSBOYXQgKCkgKCkpIChkYXRhIE5hdCAoKSAoKSkpICh2YXIgMikpKSkpKSAoYnJhbmNoIHJlZmxleGl2ZSAxIChsYW0gdW5yZXN0cmljdGVkIChhcHAgKGxhbSB1bnJlc3RyaWN0ZWQgKGRhdGEgTmF0ICgpICgpKSAoZGF0YSBOYXQgKCkgKCkpKSAoY3RvciBaKSkgKHZhciAwKSkpKSAoY3RvciBGKSkjNjU=	pieces=term::(app (case (ctor reflexive (data Nat () ()) (ctor Z)) (lam unrestricted (data Nat () ()) (lam unrestricted (data Nat () ()) (lam unrestricted (data Equivalent ((data Nat () ())) ((var 1) (var 0))) (pi unrestricted (app (lam unrestricted (data Nat () ()) (data Nat () ())) (var 2)) (app (lam unrestricted (data Nat () ()) (data Nat () ())) (var 2)))))) (branch reflexive 1 (lam unrestricted (app (lam unrestricted (data Nat () ()) (data Nat () ())) (ctor Z)) (var 0)))) (ctor F))
antigen-record	kind=malformed	assay=term/rejection	label=ill_typed	seed=-	note=malformed (must reject): unknown global	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9yZWplY3Rpb258dGVybShnbG9iYWwgbm9zdWNoZGVmKSM2Ng==	pieces=term::(global nosuchdef)
antigen-record	kind=malformed	assay=term/rejection	label=ill_typed	seed=-	note=malformed (must reject): case scrutinee not data	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9yZWplY3Rpb258dGVybShjYXNlIChmbG9hdCAtMC41KSAobGFtIHVucmVzdHJpY3RlZCAoZGF0YSBOYXQgKCkgKCkpIChkYXRhIE5hdCAoKSAoKSkpKSM2Nw==	pieces=term::(case (float -0.5) (lam unrestricted (data Nat () ()) (data Nat () ())))
antigen-record	kind=malformed	assay=term/rejection	label=ill_typed	seed=-	note=malformed (must reject): unknown family	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9yZWplY3Rpb258dGVybShkYXRhIE5vU3VjaEZhbWlseSAoKSAoKSkjNjg=	pieces=term::(data NoSuchFamily () ())
antigen-record	kind=malformed	assay=term/rejection	label=ill_typed	seed=-	note=malformed (must reject): case with unknown-ctor branch	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9yZWplY3Rpb258dGVybShjYXNlIChjdG9yIFopIChsYW0gdW5yZXN0cmljdGVkIChkYXRhIE5hdCAoKSAoKSkgKGRhdGEgTmF0ICgpICgpKSkgKGJyYW5jaCBaIDAgKGN0b3IgWikpIChicmFuY2ggUyAxIChjdG9yIFopKSAoYnJhbmNoIG5vc3VjaGN0b3IgMCAoY3RvciBaKSkpIzY5	pieces=term::(case (ctor Z) (lam unrestricted (data Nat () ()) (data Nat () ())) (branch Z 0 (ctor Z)) (branch S 1 (ctor Z)) (branch nosuchctor 0 (ctor Z)))
antigen-record	kind=malformed	assay=term/rejection	label=ill_typed	seed=-	note=malformed (must reject): case motive returns an unknown family	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9yZWplY3Rpb258dGVybShjYXNlIChjdG9yIFopIChsYW0gdW5yZXN0cmljdGVkIChkYXRhIE5hdCAoKSAoKSkgKGRhdGEgTm9TdWNoRmFtaWx5ICgpICgpKSkgKGJyYW5jaCBaIDAgKGN0b3IgWikpIChicmFuY2ggUyAxIChjdG9yIFopKSkjNzA=	pieces=term::(case (ctor Z) (lam unrestricted (data Nat () ()) (data NoSuchFamily () ())) (branch Z 0 (ctor Z)) (branch S 1 (ctor Z)))
antigen-record	kind=conv_pair	assay=conv/decision	label=distinct	seed=-	note=nvar vs napp head mismatch (146)	scaffold=g3QAAAACbQAAAANjdHhhA20AAAAGZXhwZWN0dwVmYWxzZQ==	key=Y29udi9kZWNpc2lvbnx0MSh2YXIgMCl8dDIoYXBwICh2YXIgMSkgKHR5cGUgMCkpIzcx	pieces=t1::(var 0);;t2::(app (var 1) (type 0))
antigen-record	kind=conv_pair	assay=conv/decision	label=convertible	seed=-	note=S/Z tower vs compact-lit (91)	scaffold=g3QAAAACbQAAAANjdHhhA20AAAAGZXhwZWN0dwR0cnVl	key=Y29udi9kZWNpc2lvbnx0MShjdG9yIFMgKGN0b3IgUyAoY3RvciBaKSkpfHQyKG5hdCAyKSM3Mg==	pieces=t1::(ctor S (ctor S (ctor Z)));;t2::(nat 2)
antigen-record	kind=conv_pair	assay=conv/decision	label=distinct	seed=-	note=case first vs second component, branch-body mismatch (150)	scaffold=g3QAAAACbQAAAANjdHhhA20AAAAGZXhwZWN0dwVmYWxzZQ==	key=Y29udi9kZWNpc2lvbnx0MShjYXNlICh2YXIgMCkgKGxhbSB1bnJlc3RyaWN0ZWQgKGRhdGEgU2lnbWEgKChkYXRhIE5hdCAoKSAoKSkgKGxhbSB1bnJlc3RyaWN0ZWQgKGRhdGEgTmF0ICgpICgpKSAoZGF0YSBOYXQgKCkgKCkpKSkgKCkpIChkYXRhIE5hdCAoKSAoKSkpIChicmFuY2ggbWtfcGFpciAyICh2YXIgMSkpKXx0MihjYXNlICh2YXIgMCkgKGxhbSB1bnJlc3RyaWN0ZWQgKGRhdGEgU2lnbWEgKChkYXRhIE5hdCAoKSAoKSkgKGxhbSB1bnJlc3RyaWN0ZWQgKGRhdGEgTmF0ICgpICgpKSAoZGF0YSBOYXQgKCkgKCkpKSkgKCkpIChkYXRhIE5hdCAoKSAoKSkpIChicmFuY2ggbWtfcGFpciAyICh2YXIgMCkpKSM3Mw==	pieces=t1::(case (var 0) (lam unrestricted (data Sigma ((data Nat () ()) (lam unrestricted (data Nat () ()) (data Nat () ()))) ()) (data Nat () ())) (branch mk_pair 2 (var 1)));;t2::(case (var 0) (lam unrestricted (data Sigma ((data Nat () ()) (lam unrestricted (data Nat () ()) (data Nat () ()))) ()) (data Nat () ())) (branch mk_pair 2 (var 0)))
antigen-record	kind=conv_pair	assay=conv/decision	label=convertible	seed=-	note=app-arg vtype (187)	scaffold=g3QAAAACbQAAAANjdHhhA20AAAAGZXhwZWN0dwR0cnVl	key=Y29udi9kZWNpc2lvbnx0MShhcHAgKHZhciAwKSAodHlwZSAwKSl8dDIoYXBwICh2YXIgMCkgKHR5cGUgMCkpIzc0	pieces=t1::(app (var 0) (type 0));;t2::(app (var 0) (type 0))
antigen-record	kind=conv_pair	assay=conv/decision	label=convertible	seed=-	note=η neutral-vs-λ (70,108)	scaffold=g3QAAAACbQAAAANjdHhhA20AAAAGZXhwZWN0dwR0cnVl	key=Y29udi9kZWNpc2lvbnx0MSh2YXIgMCl8dDIobGFtIHVucmVzdHJpY3RlZCAodHlwZSAwKSAoYXBwICh2YXIgMSkgKHZhciAwKSkpIzc1	pieces=t1::(var 0);;t2::(lam unrestricted (type 0) (app (var 1) (var 0)))
antigen-record	kind=conv_pair	assay=conv/decision	label=distinct	seed=-	note=compact-nat distinct literals (85)	scaffold=g3QAAAACbQAAAANjdHhhA20AAAAGZXhwZWN0dwVmYWxzZQ==	key=Y29udi9kZWNpc2lvbnx0MShuYXQgMil8dDIobmF0IDMpIzc2	pieces=t1::(nat 2);;t2::(nat 3)
antigen-record	kind=conv_pair	assay=conv/decision	label=convertible	seed=-	note=compact-lit vs S/Z tower (88)	scaffold=g3QAAAACbQAAAANjdHhhA20AAAAGZXhwZWN0dwR0cnVl	key=Y29udi9kZWNpc2lvbnx0MShuYXQgMSl8dDIoY3RvciBTIChjdG9yIFopKSM3Nw==	pieces=t1::(nat 1);;t2::(ctor S (ctor Z))
antigen-record	kind=conv_pair	assay=conv/decision	label=distinct	seed=-	note=λ-vs-non-λ (109)	scaffold=g3QAAAACbQAAAANjdHhhA20AAAAGZXhwZWN0dwVmYWxzZQ==	key=Y29udi9kZWNpc2lvbnx0MShsYW0gdW5yZXN0cmljdGVkICh0eXBlIDApICh2YXIgMSkpfHQyKHR5cGUgMCkjNzg=	pieces=t1::(lam unrestricted (type 0) (var 1));;t2::(type 0)
antigen-record	kind=conv_pair	assay=conv/decision	label=convertible	seed=-	note=app-arg vfloat_type (190)	scaffold=g3QAAAACbQAAAANjdHhhA20AAAAGZXhwZWN0dwR0cnVl	key=Y29udi9kZWNpc2lvbnx0MShhcHAgKHZhciAwKSAoZmxvYXQtdHlwZSkpfHQyKGFwcCAodmFyIDApIChmbG9hdC10eXBlKSkjNzk=	pieces=t1::(app (var 0) (float-type));;t2::(app (var 0) (float-type))
antigen-record	kind=conv_pair	assay=conv/decision	label=convertible	seed=-	note=app-arg vλ fallback → conv_struct η (199)	scaffold=g3QAAAACbQAAAANjdHhhA20AAAAGZXhwZWN0dwR0cnVl	key=Y29udi9kZWNpc2lvbnx0MShhcHAgKHZhciAwKSAobGFtIHVucmVzdHJpY3RlZCAodHlwZSAwKSAodHlwZSAwKSkpfHQyKGFwcCAodmFyIDApIChsYW0gdW5yZXN0cmljdGVkICh0eXBlIDApICh0eXBlIDApKSkjODA=	pieces=t1::(app (var 0) (lam unrestricted (type 0) (type 0)));;t2::(app (var 0) (lam unrestricted (type 0) (type 0)))
antigen-record	kind=conv_pair	assay=conv/decision	label=convertible	seed=-	note=app-arg vint (189)	scaffold=g3QAAAACbQAAAANjdHhhA20AAAAGZXhwZWN0dwR0cnVl	key=Y29udi9kZWNpc2lvbnx0MShhcHAgKHZhciAwKSAoaW50IC03KSl8dDIoYXBwICh2YXIgMCkgKGludCAtNykpIzgx	pieces=t1::(app (var 0) (int -7));;t2::(app (var 0) (int -7))
antigen-record	kind=conv_pair	assay=conv/decision	label=convertible	seed=-	note=out-of-ctx var → neutral (eval)	scaffold=g3QAAAACbQAAAANjdHhhA20AAAAGZXhwZWN0dwR0cnVl	key=Y29udi9kZWNpc2lvbnx0MSh2YXIgNSl8dDIodmFyIDUpIzgy	pieces=t1::(var 5);;t2::(var 5)
antigen-record	kind=conv_pair	assay=conv/decision	label=convertible	seed=-	note=app-arg vint_type (188)	scaffold=g3QAAAACbQAAAANjdHhhA20AAAAGZXhwZWN0dwR0cnVl	key=Y29udi9kZWNpc2lvbnx0MShhcHAgKHZhciAwKSAoaW50LXR5cGUpKXx0MihhcHAgKHZhciAwKSAoaW50LXR5cGUpKSM4Mw==	pieces=t1::(app (var 0) (int-type));;t2::(app (var 0) (int-type))
antigen-record	kind=conv_pair	assay=conv/decision	label=convertible	seed=-	note=app-arg vnat no-δ fast path (194)	scaffold=g3QAAAACbQAAAANjdHhhA20AAAAGZXhwZWN0dwR0cnVl	key=Y29udi9kZWNpc2lvbnx0MShhcHAgKHZhciAwKSAobmF0IDMpKXx0MihhcHAgKHZhciAwKSAobmF0IDMpKSM4NA==	pieces=t1::(app (var 0) (nat 3));;t2::(app (var 0) (nat 3))
antigen-record	kind=conv_pair	assay=conv/decision	label=convertible	seed=-	note=app-arg vdata (193)	scaffold=g3QAAAACbQAAAANjdHhhA20AAAAGZXhwZWN0dwR0cnVl	key=Y29udi9kZWNpc2lvbnx0MShhcHAgKHZhciAwKSAoZGF0YSBOYXQgKCkgKCkpKXx0MihhcHAgKHZhciAwKSAoZGF0YSBOYXQgKCkgKCkpKSM4NQ==	pieces=t1::(app (var 0) (data Nat () ()));;t2::(app (var 0) (data Nat () ()))
antigen-record	kind=conv_pair	assay=conv/decision	label=convertible	seed=-	note=app-arg vfloat (191)	scaffold=g3QAAAACbQAAAANjdHhhA20AAAAGZXhwZWN0dwR0cnVl	key=Y29udi9kZWNpc2lvbnx0MShhcHAgKHZhciAwKSAoZmxvYXQgMy4wKSl8dDIoYXBwICh2YXIgMCkgKGZsb2F0IDMuMCkpIzg2	pieces=t1::(app (var 0) (float 3.0));;t2::(app (var 0) (float 3.0))
antigen-record	kind=check_mode	assay=check/verdict	label=reject	seed=-	note=check nosuchctor : List Nat — checking-mode unknown constructor (unknown_ctor)	scaffold=g3QAAAABbQAAAAhjdHhfdmFyc2EA	key=Y2hlY2svdmVyZGljdHx0ZXJtKGN0b3Igbm9zdWNoY3Rvcil8dHlwZShkYXRhIExpc3QgKChkYXRhIE5hdCAoKSAoKSkpICgpKSM4Nw==	pieces=term::(ctor nosuchctor);;type::(data List ((data Nat () ())) ())
antigen-record	kind=delta_reduce	assay=delta/nf	label=opts_reject	seed=-	note=opts/reject: :mode must be :whnf|:nf (rejects a valid :delta atom used as :mode)	scaffold=g3QAAAABbQAAAARvcHRzbAAAAAFoAncEbW9kZXcJY2VydGlmaWVkag==	key=ZGVsdGEvbmZ8Izg4	pieces=
antigen-record	kind=delta_reduce	assay=delta/nf	label=reduces	seed=-	note=ncase/branch_miss (unfolded): donly (S Z) unfolds to a case with no S arm — reduce_unfolded freezes it, never crashes	scaffold=-	key=ZGVsdGEvbmZ8dGVybShhcHAgKGdsb2JhbCBkb25seSkgKGN0b3IgUyAoY3RvciBaKSkpfGV4cGVjdGVkKGFwcCAoZ2xvYmFsIGRvbmx5KSAoY3RvciBTIChjdG9yIFopKSkjODk=	pieces=term::(app (global donly) (ctor S (ctor Z)));;expected::(app (global donly) (ctor S (ctor Z)))
antigen-record	kind=delta_reduce	assay=delta/nf	label=fuel_probe	seed=-	note=fuel/exhausted: idnat^3 Z needs 3 δ-steps; a 2-step budget reports :fuel_exhausted, never a truncated wrong value	scaffold=g3QAAAACbQAAAARvcHRzbAAAAAFoAncEZnVlbGECam0AAAAEd2FudHcOZnVlbF9leGhhdXN0ZWQ=	key=ZGVsdGEvbmZ8dGVybShhcHAgKGdsb2JhbCBpZG5hdCkgKGFwcCAoZ2xvYmFsIGlkbmF0KSAoYXBwIChnbG9iYWwgaWRuYXQpIChjdG9yIFopKSkpfGV4cGVjdGVkKGN0b3IgWikjOTA=	pieces=term::(app (global idnat) (app (global idnat) (app (global idnat) (ctor Z))));;expected::(ctor Z)
antigen-record	kind=delta_reduce	assay=delta/nf	label=reduces	seed=-	note=builtin/struct_eq: struct_eq Int 3 4 → False (δ-fold via the audited literal table)	scaffold=-	key=ZGVsdGEvbmZ8dGVybShhcHAgKGFwcCAoYXBwIChnbG9iYWwgc3RydWN0X2VxKSAoaW50LXR5cGUpKSAoaW50IDMpKSAoaW50IDQpKXxleHBlY3RlZChjdG9yIFN0ZC5Cb29sI0ZhbHNlKSM5MQ==	pieces=term::(app (app (app (global struct_eq) (int-type)) (int 3)) (int 4));;expected::(ctor Std.Bool#False)
antigen-record	kind=delta_reduce	assay=delta/nf	label=reduces	seed=-	note=builtin/arity_stuck: struct_eq Int 5 (unsaturated, 2 of 3 args) stays neutral — never a bogus fold	scaffold=-	key=ZGVsdGEvbmZ8dGVybShhcHAgKGFwcCAoZ2xvYmFsIHN0cnVjdF9lcSkgKGludC10eXBlKSkgKGludCA1KSl8ZXhwZWN0ZWQoYXBwIChhcHAgKGdsb2JhbCBzdHJ1Y3RfZXEpIChpbnQtdHlwZSkpIChpbnQgNSkpIzky	pieces=term::(app (app (global struct_eq) (int-type)) (int 5));;expected::(app (app (global struct_eq) (int-type)) (int 5))
antigen-record	kind=delta_reduce	assay=delta/nf	label=reduces	seed=-	note=builtin/struct_ne: struct_ne Int 5 5 → False (δ-fold via the audited literal table)	scaffold=-	key=ZGVsdGEvbmZ8dGVybShhcHAgKGFwcCAoYXBwIChnbG9iYWwgc3RydWN0X25lKSAoaW50LXR5cGUpKSAoaW50IDUpKSAoaW50IDUpKXxleHBlY3RlZChjdG9yIFN0ZC5Cb29sI0ZhbHNlKSM5Mw==	pieces=term::(app (app (app (global struct_ne) (int-type)) (int 5)) (int 5));;expected::(ctor Std.Bool#False)
antigen-record	kind=delta_reduce	assay=delta/nf	label=opts_reject	seed=-	note=opts/reject: :delta must be :certified|:none (rejects a valid :mode atom used as :delta)	scaffold=g3QAAAABbQAAAARvcHRzbAAAAAFoAncFZGVsdGF3BHdobmZq	key=ZGVsdGEvbmZ8Izk0	pieces=
antigen-record	kind=delta_reduce	assay=delta/nf	label=opts_reject	seed=-	note=opts/reject: :fuel must be a positive integer or :infinity (0 is rejected)	scaffold=g3QAAAABbQAAAARvcHRzbAAAAAFoAncEZnVlbGEAag==	key=ZGVsdGEvbmZ8Izk1	pieces=
antigen-record	kind=delta_reduce	assay=delta/nf	label=reduces	seed=-	note=ncase/branch_miss (direct): case (idnat (S Z)) {Z->Z} has no S arm — unfold_certified_head freezes it, never crashes	scaffold=-	key=ZGVsdGEvbmZ8dGVybShjYXNlIChhcHAgKGdsb2JhbCBpZG5hdCkgKGN0b3IgUyAoY3RvciBaKSkpIChsYW0gdW5yZXN0cmljdGVkIChkYXRhIE5hdCAoKSAoKSkgKGRhdGEgTmF0ICgpICgpKSkgKGJyYW5jaCBaIDAgKGN0b3IgWikpKXxleHBlY3RlZChjYXNlIChhcHAgKGdsb2JhbCBpZG5hdCkgKGN0b3IgUyAoY3RvciBaKSkpIChsYW0gdW5yZXN0cmljdGVkIChkYXRhIE5hdCAoKSAoKSkgKGRhdGEgTmF0ICgpICgpKSkgKGJyYW5jaCBaIDAgKGN0b3IgWikpKSM5Ng==	pieces=term::(case (app (global idnat) (ctor S (ctor Z))) (lam unrestricted (data Nat () ()) (data Nat () ())) (branch Z 0 (ctor Z)));;expected::(case (app (global idnat) (ctor S (ctor Z))) (lam unrestricted (data Nat () ()) (data Nat () ())) (branch Z 0 (ctor Z)))
antigen-record	kind=delta_reduce	assay=delta/nf	label=opts_reject	seed=-	note=opts/reject: :stuck_cases must be :preserve (any other value is rejected — MatchError, rescued and re-raised)	scaffold=g3QAAAABbQAAAARvcHRzbAAAAAFoAncLc3R1Y2tfY2FzZXN3BWZhbHNlag==	key=ZGVsdGEvbmZ8Izk3	pieces=
antigen-record	kind=typed_term	assay=kernel/effect_inert	label=well_typed	seed=-	note=pure(3): a trivial computation	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=a2VybmVsL2VmZmVjdF9pbmVydHx0eXBlKGVmZmVjdC10eXBlIChkYXRhIEludCAoKSAoKSkpfHRlcm0oZWZmZWN0LXB1cmUgKGludCAzKSkjOTg=	pieces=type::(effect-type (data Int () ()));;term::(effect-pure (int 3))
antigen-record	kind=typed_term	assay=kernel/effect_inert	label=well_typed	seed=-	note=bare Effect(Int): the type former is inert	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=a2VybmVsL2VmZmVjdF9pbmVydHx0eXBlKGVmZmVjdC10eXBlIChkYXRhIEludCAoKSAoKSkpfHRlcm0oZWZmZWN0LXR5cGUgKGRhdGEgSW50ICgpICgpKSkjOTk=	pieces=type::(effect-type (data Int () ()));;term::(effect-type (data Int () ()))
antigen-record	kind=typed_term	assay=kernel/effect_inert	label=well_typed	seed=-	note=bind(bind(pure(3), λx. pure(x)), λy. pure(y)): nesting (commuting-conversion catcher)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=a2VybmVsL2VmZmVjdF9pbmVydHx0eXBlKGVmZmVjdC10eXBlIChkYXRhIEludCAoKSAoKSkpfHRlcm0oZWZmZWN0LWJpbmQgKGVmZmVjdC1iaW5kIChlZmZlY3QtcHVyZSAoaW50IDMpKSAobGFtIHVucmVzdHJpY3RlZCAoZGF0YSBJbnQgKCkgKCkpIChlZmZlY3QtcHVyZSAodmFyIDApKSkpIChsYW0gdW5yZXN0cmljdGVkIChkYXRhIEludCAoKSAoKSkgKGVmZmVjdC1wdXJlICh2YXIgMCkpKSkjMTAw	pieces=type::(effect-type (data Int () ()));;term::(effect-bind (effect-bind (effect-pure (int 3)) (lam unrestricted (data Int () ()) (effect-pure (var 0)))) (lam unrestricted (data Int () ()) (effect-pure (var 0))))
antigen-record	kind=dot_forcing	assay=forcing/dot	label=reject	seed=-	note=Sq mksq {n=.(S Z)} vs forced Z — multi-index reject	scaffold=g3QAAAAEbQAAAAVjbmFtZW0AAAAEbWtzcW0AAAAIY3R4X3ZhcnNhAG0AAAAGZmFtaWx5bQAAAAJTcW0AAAAEbmFtZW0AAAABbg==	key=Zm9yY2luZy9kb3R8aWR4OjAoY3RvciBaKXxpZHg6MShjdG9yIFopfHdyaXR0ZW4oY3RvciBTIChjdG9yIFopKSMxMDE=	pieces=idx:0::(ctor Z);;idx:1::(ctor Z);;written::(ctor S (ctor Z))
antigen-record	kind=dot_forcing	assay=forcing/dot	label=reject	seed=-	note=Vec vcons {n=.Z} vs forced S Z — reject on differing forced value	scaffold=g3QAAAAEbQAAAAVjbmFtZW0AAAAFdmNvbnNtAAAACGN0eF92YXJzYQBtAAAABmZhbWlseW0AAAADVmVjbQAAAARuYW1lbQAAAAFu	key=Zm9yY2luZy9kb3R8aWR4OjAoY3RvciBTIChjdG9yIFMgKGN0b3IgWikpKXx3cml0dGVuKGN0b3IgWikjMTAy	pieces=idx:0::(ctor S (ctor S (ctor Z)));;written::(ctor Z)
antigen-record	kind=decode_probe	assay=serialize/decode	label=invalid_sexp	seed=-	note=decode probe (invalid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAADNSA2	key=c2VyaWFsaXplL2RlY29kZXwjMTAz	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=invalid_sexp	seed=-	note=decode probe (invalid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAAEImFiYw==	key=c2VyaWFsaXplL2RlY29kZXwjMTA0	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=invalid_sexp	seed=-	note=decode probe (invalid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAAEKGludA==	key=c2VyaWFsaXplL2RlY29kZXwjMTA1	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=valid_sexp	seed=-	note=decode probe (valid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAALKGZsb2F0IDEuNSk=	key=c2VyaWFsaXplL2RlY29kZXwjMTA2	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=valid_sexp	seed=-	note=decode probe (valid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAANKGhvbGUgImFcImIiKQ==	key=c2VyaWFsaXplL2RlY29kZXwjMTA3	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=valid_sexp	seed=-	note=decode probe (valid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAAHKGludCAwKQ==	key=c2VyaWFsaXplL2RlY29kZXwjMTA4	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=valid_sexp	seed=-	note=decode probe (valid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAAHKG5hdCAwKQ==	key=c2VyaWFsaXplL2RlY29kZXwjMTA5	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=invalid_sexp	seed=-	note=decode probe (invalid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAARKGFwcCBmb28gKGludCA1KSk=	key=c2VyaWFsaXplL2RlY29kZXwjMTEw	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=invalid_sexp	seed=-	note=decode probe (invalid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAAA	key=c2VyaWFsaXplL2RlY29kZXwjMTEx	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=invalid_sexp	seed=-	note=decode probe (invalid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAAQKGN0b3IgRm9vICh6enopKQ==	key=c2VyaWFsaXplL2RlY29kZXwjMTEy	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=valid_sexp	seed=-	note=decode probe (valid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAALKGJvdW5kZWQgMCk=	key=c2VyaWFsaXplL2RlY29kZXwjMTEz	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=invalid_sexp	seed=-	note=decode probe (invalid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAAtKGNhc2UgKHZhciAwKSAodHlwZSAwKSAoYnJhbmNoIFogLTMgKHZhciAwKSkp	key=c2VyaWFsaXplL2RlY29kZXwjMTE0	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=valid_sexp	seed=-	note=decode probe (valid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAAIKGFic3VyZCk=	key=c2VyaWFsaXplL2RlY29kZXwjMTE1	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=valid_sexp	seed=-	note=decode probe (valid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAAKKGludC10eXBlKQ==	key=c2VyaWFsaXplL2RlY29kZXwjMTE2	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=invalid_sexp	seed=-	note=decode probe (invalid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAApKGNhc2UgKHZhciAwKSAodmFyIDApIChicmFuY2ggWiAwICh6enopKSk=	key=c2VyaWFsaXplL2RlY29kZXwjMTE3	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=valid_sexp	seed=-	note=decode probe (valid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAAIKHR5cGUgMCk=	key=c2VyaWFsaXplL2RlY29kZXwjMTE4	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=valid_sexp	seed=-	note=decode probe (valid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAANKGhvbGUgImFcXGIiKQ==	key=c2VyaWFsaXplL2RlY29kZXwjMTE5	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=invalid_sexp	seed=-	note=decode probe (invalid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAACKSk=	key=c2VyaWFsaXplL2RlY29kZXwjMTIw	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=invalid_sexp	seed=-	note=decode probe (invalid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAAaKGNhc2UgKHZhciAwKSAodmFyIDApIGZvbyk=	key=c2VyaWFsaXplL2RlY29kZXwjMTIx	pieces=
antigen-record	kind=typed_term	assay=term/infer_check	label=well_typed	seed=-	note=type former	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9pbmZlcl9jaGVja3x0eXBlKHR5cGUgMCl8dGVybShkYXRhIFNpZ21hICgoZmxvYXQtdHlwZSkgKGxhbSB1bnJlc3RyaWN0ZWQgKGZsb2F0LXR5cGUpIChmbG9hdC10eXBlKSkpICgpKSMxMjI=	pieces=type::(type 0);;term::(data Sigma ((float-type) (lam unrestricted (float-type) (float-type))) ())
antigen-record	kind=typed_term	assay=term/infer_check	label=well_typed	seed=-	note=type former	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9pbmZlcl9jaGVja3x0eXBlKHR5cGUgMCl8dGVybShkYXRhIFNpZ21hICgoaW50LXR5cGUpIChsYW0gdW5yZXN0cmljdGVkIChpbnQtdHlwZSkgKGludC10eXBlKSkpICgpKSMxMjM=	pieces=type::(type 0);;term::(data Sigma ((int-type) (lam unrestricted (int-type) (int-type))) ())
antigen-record	kind=family	assay=universes	label=ill_typed	seed=-	note=parameterized wrong result-param arity	scaffold=g3QAAAAFbQAAAAVjdG9yc2wAAAABdAAAAAVtAAAACWFyZ19uYW1lc2wAAAABbQAAAAF4am0AAAAEbmFtZW0AAAACcGNtAAAACnF1YW50aXRpZXNsAAAAAW0AAAAEbWFueWptAAAACnJpZHhfY291bnRhAW0AAAAMcnBhcmFtX2NvdW50YQBqbQAAAA9mYW1faW5kZXhfbmFtZXNsAAAAAW0AAAABbmptAAAACWZhbV9sZXZlbGEAbQAAAAhmYW1fbmFtZW0AAAABUG0AAAAPZmFtX3BhcmFtX25hbWVzbAAAAAFtAAAAAWFq	key=dW5pdmVyc2VzfGZhbV9wYXJhbTowKHR5cGUgMCl8ZmFtX2luZGV4OjAoZGF0YSBJbnQgKCkgKCkpfGN0b3I6MDphcmc6MCh2YXIgMCl8Y3RvcjowOnJpZHg6MChpbnQgLTIpIzEyNA==	pieces=fam_param:0::(type 0);;fam_index:0::(data Int () ());;ctor:0:arg:0::(var 0);;ctor:0:ridx:0::(int -2)
antigen-record	kind=family	assay=universes	label=ill_typed	seed=-	note=parameterized non-uniform (result param = x)	scaffold=g3QAAAAFbQAAAAVjdG9yc2wAAAABdAAAAAVtAAAACWFyZ19uYW1lc2wAAAABbQAAAAF4am0AAAAEbmFtZW0AAAACcGNtAAAACnF1YW50aXRpZXNsAAAAAW0AAAAEbWFueWptAAAACnJpZHhfY291bnRhAW0AAAAMcnBhcmFtX2NvdW50YQFqbQAAAA9mYW1faW5kZXhfbmFtZXNsAAAAAW0AAAABbmptAAAACWZhbV9sZXZlbGEAbQAAAAhmYW1fbmFtZW0AAAABUG0AAAAPZmFtX3BhcmFtX25hbWVzbAAAAAFtAAAAAWFq	key=dW5pdmVyc2VzfGZhbV9wYXJhbTowKHR5cGUgMCl8ZmFtX2luZGV4OjAoZmxvYXQtdHlwZSl8Y3RvcjowOmFyZzowKHZhciAwKXxjdG9yOjA6cmlkeDowKGZsb2F0IC00LjUpfGN0b3I6MDpycGFyYW06MCh2YXIgMCkjMTI1	pieces=fam_param:0::(type 0);;fam_index:0::(float-type);;ctor:0:arg:0::(var 0);;ctor:0:ridx:0::(float -4.5);;ctor:0:rparam:0::(var 0)
antigen-record	kind=family	assay=universes	label=ill_typed	seed=-	note=arg-bearing ctor with non-type field	scaffold=g3QAAAAFbQAAAAVjdG9yc2wAAAABdAAAAAVtAAAACWFyZ19uYW1lc2wAAAABbQAAAAF4am0AAAAEbmFtZW0AAAADbWtpbQAAAApxdWFudGl0aWVzbAAAAAFtAAAADHVucmVzdHJpY3RlZGptAAAACnJpZHhfY291bnRhAW0AAAAMcnBhcmFtX2NvdW50YQBqbQAAAA9mYW1faW5kZXhfbmFtZXNsAAAAAW0AAAABbmptAAAACWZhbV9sZXZlbGEAbQAAAAhmYW1fbmFtZW0AAAAESWR4SW0AAAAPZmFtX3BhcmFtX25hbWVzag==	key=dW5pdmVyc2VzfGZhbV9pbmRleDowKGZsb2F0LXR5cGUpfGN0b3I6MDphcmc6MChmbG9hdCAwLjApfGN0b3I6MDpyaWR4OjAoZmxvYXQgLTEuNSkjMTI2	pieces=fam_index:0::(float-type);;ctor:0:arg:0::(float 0.0);;ctor:0:ridx:0::(float -1.5)
antigen-record	kind=elab_program	assay=elab/metamorphic	label=none	seed=-	note=computed_idx/rebuild invariant under alpha_rename	scaffold=g3QAAAAEbQAAAAhiYXNlX3NyY20AAAGSbW9kIFAKICB0eXBlIE5hdCA9IFogfCBTKE5hdCkKICB0eXBlIFNMaXN0ID0gU05pbCB8IFNDb25zKE5hdCwgU0xpc3QpCiAgZm4gYXBwKHhzOiBTTGlzdCwgeXM6IFNMaXN0KSAtPiBTTGlzdCA9IG1hdGNoIHhzCiAgICBTTmlsKCkgLT4geXMKICAgIFNDb25zKGgsIHQpIC0+IFNDb25zKGgsIGFwcCh0LCB5cykpCiAgdHlwZSBGIGluZGljZXMgKHhzOiBTTGlzdCkKICAgIGxlYWYgOiBGKFNOaWwoKSkKICAgIG1rIDogRihhcykgLT4gRihicykgLT4gRihhcHAoYXMsIGJzKSkKICBmbiBnKHtwOiBTTGlzdH0sIHtxOiBTTGlzdH0sIHY6IEYoYXBwKHAsIHEpKSkgLT4gRihhcHAocCwgcSkpID0KICAgIG1hdGNoIHYKICAgICAgbGVhZigpIC0+IGxlYWYoKQogICAgICBtayhsLCByKSAtPiBtayhsLCByKQplbmQKbQAAAAJpZG0AAAAUY29tcHV0ZWRfaWR4L3JlYnVpbGRtAAAACXRyYW5zZm9ybW0AAAAMYWxwaGFfcmVuYW1lbQAAAAt2YXJpYW50X3NyY20AAAGWbW9kIFAKICB0eXBlIE5hdCA9IFogfCBTKE5hdCkKICB0eXBlIFNMaXN0ID0gU05pbCB8IFNDb25zKE5hdCwgU0xpc3QpCiAgZm4gYXBwKHhzOiBTTGlzdCwgeXM6IFNMaXN0KSAtPiBTTGlzdCA9IG1hdGNoIHhzCiAgICBTTmlsKCkgLT4geXMKICAgIFNDb25zKGgsIHQpIC0+IFNDb25zKGgsIGFwcCh0LCB5cykpCiAgdHlwZSBGIGluZGljZXMgKHhzOiBTTGlzdCkKICAgIGxlYWYgOiBGKFNOaWwoKSkKICAgIG1rIDogRihhcykgLT4gRihicykgLT4gRihhcHAoYXMsIGJzKSkKICBmbiBnKHtwOiBTTGlzdH0sIHtxOiBTTGlzdH0sIHZ2MDogRihhcHAocCwgcSkpKSAtPiBGKGFwcChwLCBxKSkgPQogICAgbWF0Y2ggdnYwCiAgICAgIGxlYWYoKSAtPiBsZWFmKCkKICAgICAgbWsobCwgcikgLT4gbWsobCwgcikKZW5kCg==	key=ZWxhYi9tZXRhbW9ycGhpY3wjMTI3	pieces=
antigen-record	kind=elab_program	assay=elab/completeness	label=well_typed	seed=-	note=goal Equivalent(NV(n), v, v), reflexive(v)	scaffold=g3QAAAACbQAAAAJpZG0AAAAXZXFfdmFsdWUvdmFyL3JlZmxfc2NydXRtAAAAA3NyY20AAAHUbW9kIFAKICB0eXBlIE5hdCA9IFogfCBTKE5hdCkKICB0eXBlIFNOYXQgaW5kaWNlcyAobjogTmF0KQogICAgc3plcm8gOiBTTmF0KFopCiAgICBzc3VjIDogU05hdChuKSAtPiBTTmF0KFMobikpCiAgdHlwZSBOViBpbmRpY2VzIChuOiBOYXQpCiAgICB2eiA6IE5WKFopCiAgICB2cyA6IFNOYXQobikgLT4gTlYoUyhuKSkKICBmbiB0b1MobTogTmF0KSAtPiBTTmF0KG0pID0gbWF0Y2ggbQogICAgWigpIC0+IHN6ZXJvKCkKICAgIFMoaikgLT4gc3N1Yyh0b1MoaikpCiAgZm4gdmlldyhuOiBOYXQpIC0+IE5WKG4pID0gbWF0Y2ggbgogICAgWigpIC0+IHZ6KCkKICAgIFMobSkgLT4gdnModG9TKG0pKQogIGZuIGYoe246IE5hdH0sIHY6IE5WKG4pKSAtPiBFcXVpdmFsZW50KE5WKG4pLCB2LCB2KSA9CiAgICBtYXRjaCB2CiAgICAgIHZ6KCkgLT4gcmVmbGV4aXZlKHYpCiAgICAgIHZzKHMpIC0+IHJlZmxleGl2ZSh2KQplbmQK	key=ZWxhYi9jb21wbGV0ZW5lc3N8IzEyOA==	pieces=
antigen-record	kind=elab_program	assay=elab/soundness	label=well_typed	seed=-	note=goal Equivalent(NV(n), view(n), view(n)), computed scrutinee	scaffold=g3QAAAACbQAAAAJpZG0AAAAbZXFfdmFsdWUvY29tcHV0ZWQvcmVmbF9jdG9ybQAAAANzcmNtAAAB4W1vZCBQCiAgdHlwZSBOYXQgPSBaIHwgUyhOYXQpCiAgdHlwZSBTTmF0IGluZGljZXMgKG46IE5hdCkKICAgIHN6ZXJvIDogU05hdChaKQogICAgc3N1YyA6IFNOYXQobikgLT4gU05hdChTKG4pKQogIHR5cGUgTlYgaW5kaWNlcyAobjogTmF0KQogICAgdnogOiBOVihaKQogICAgdnMgOiBTTmF0KG4pIC0+IE5WKFMobikpCiAgZm4gdG9TKG06IE5hdCkgLT4gU05hdChtKSA9IG1hdGNoIG0KICAgIFooKSAtPiBzemVybygpCiAgICBTKGopIC0+IHNzdWModG9TKGopKQogIGZuIHZpZXcobjogTmF0KSAtPiBOVihuKSA9IG1hdGNoIG4KICAgIFooKSAtPiB2eigpCiAgICBTKG0pIC0+IHZzKHRvUyhtKSkKICBmbiBmKG46IE5hdCkgLT4gRXF1aXZhbGVudChOVihuKSwgdmlldyhuKSwgdmlldyhuKSkgPQogICAgbWF0Y2ggdmlldyhuKQogICAgICB2eigpIC0+IHJlZmxleGl2ZSh2eigpKQogICAgICB2cyhzKSAtPiByZWZsZXhpdmUodnMocykpCmVuZAo=	key=ZWxhYi9zb3VuZG5lc3N8IzEyOQ==	pieces=
antigen-record	kind=elab_program	assay=elab/dot_forcing	label=accept	seed=-	note=right dot on the carried-eq path (over-rejection guard)	scaffold=g3QAAAADbQAAAAZleHBlY3R3BmFjY2VwdG0AAAACaWRtAAAAFGZvcmNlZC9jYXJyaWVkL3JpZ2h0bQAAAANzcmNtAAABpG1vZCBQCiAgdHlwZSBOYXQgPSBaIHwgUyhOYXQpCiAgdHlwZSBTTGlzdCA9IFNOaWwgfCBTQ29ucyhOYXQsIFNMaXN0KQogIGZuIGFwcCh4czogU0xpc3QsIHlzOiBTTGlzdCkgLT4gU0xpc3QgPSBtYXRjaCB4cwogICAgU05pbCgpIC0+IHlzCiAgICBTQ29ucyhoLCB0KSAtPiBTQ29ucyhoLCBhcHAodCwgeXMpKQogIHR5cGUgSCBpbmRpY2VzIChuOiBOYXQsIHhzOiBTTGlzdCkKICAgIGhtayA6IEgoUyhtKSwgYXBwKGFzLCBicykpCiAgdHlwZSBHIGluZGljZXMgKHhzOiBTTGlzdCkKICAgIGd3cmFwIDogRyhjcykKICBmbiBnKHtqOiBOYXR9LCB7cDogU0xpc3R9LCB7cTogU0xpc3R9LCB2OiBIKFMoaiksIGFwcChwLCBxKSksIHc6IEcoYXBwKHAsIHEpKSkgLT4gTmF0ID0gbWF0Y2ggdgogICAgaG1rKHttID0gLmp9KSAtPiBaKCkKZW5kCg==	key=ZWxhYi9kb3RfZm9yY2luZ3wjMTMw	pieces=
antigen-record	kind=elab_program	assay=elab/soundness	label=well_typed	seed=-	note=boolean literal in inference position — Kernel.bool_type_value/1	scaffold=g3QAAAACbQAAAAJpZG0AAAAVbGl0X3R5cGluZy9ib29sX2luZmVybQAAAANzcmNtAAAAJW1vZCBQCiAgZm4gZmxhZygpIC0+IEJvb2wgPSB0cnVlCmVuZAo=	key=ZWxhYi9zb3VuZG5lc3N8IzEzMQ==	pieces=
antigen-record	kind=family	assay=inductive/env_roundtrip	label=well_typed	seed=-	note=Env-accessor roundtrip probe (AntigenEnv/antigenA, n=-1)	scaffold=g3QAAAAFbQAAAAVjdG9yc2wAAAABdAAAAAVtAAAACWFyZ19uYW1lc2wAAAACbQAAAAF4bQAAAAF5am0AAAAEbmFtZW0AAAAIYW50aWdlbkFtAAAACnF1YW50aXRpZXNsAAAAAm0AAAAGZXJhc2VkbQAAAAx1bnJlc3RyaWN0ZWRqbQAAAApyaWR4X2NvdW50YQFtAAAADHJwYXJhbV9jb3VudGEBam0AAAAPZmFtX2luZGV4X25hbWVzbAAAAAFtAAAAAW5qbQAAAAlmYW1fbGV2ZWxhAG0AAAAIZmFtX25hbWVtAAAACkFudGlnZW5FbnZtAAAAD2ZhbV9wYXJhbV9uYW1lc2wAAAABbQAAAAFhag==	key=aW5kdWN0aXZlL2Vudl9yb3VuZHRyaXB8ZmFtX3BhcmFtOjAodHlwZSAwKXxmYW1faW5kZXg6MChkYXRhIEludCAoKSAoKSl8Y3RvcjowOmFyZzowKHZhciAwKXxjdG9yOjA6YXJnOjEodmFyIDEpfGN0b3I6MDpyaWR4OjAoaW50IC0xKXxjdG9yOjA6cnBhcmFtOjAodmFyIDIpIzEzMg==	pieces=fam_param:0::(type 0);;fam_index:0::(data Int () ());;ctor:0:arg:0::(var 0);;ctor:0:arg:1::(var 1);;ctor:0:ridx:0::(int -1);;ctor:0:rparam:0::(var 2)
antigen-record	kind=typed_term	assay=term/normalization	label=well_typed	seed=-	note=dependent match (indexed Vec case)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQJtAAAAA3NpZ20AAAACdjE=	key=dGVybS9ub3JtYWxpemF0aW9ufGN0eDAoZGF0YSBWZWMgKCkgKCh2YXIgMCkpKXxjdHgxKGRhdGEgTmF0ICgpICgpKXx0eXBlKHR5cGUgMCl8dGVybShjYXNlICh2YXIgMCkgKGxhbSB1bnJlc3RyaWN0ZWQgKGRhdGEgTmF0ICgpICgpKSAobGFtIHVucmVzdHJpY3RlZCAoZGF0YSBWZWMgKCkgKCh2YXIgMCkpKSAodHlwZSAwKSkpIChicmFuY2ggdm5pbCAwIChmbG9hdC10eXBlKSkgKGJyYW5jaCB2Y29ucyAzIChkYXRhIEJkICgpICgpKSkpIzEzMw==	pieces=ctx0::(data Vec () ((var 0)));;ctx1::(data Nat () ());;type::(type 0);;term::(case (var 0) (lam unrestricted (data Nat () ()) (lam unrestricted (data Vec () ((var 0))) (type 0))) (branch vnil 0 (float-type)) (branch vcons 3 (data Bd () ())))
antigen-record	kind=typed_term	assay=term/normalization	label=well_typed	seed=-	note=propositional equality (inductive Equivalent)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQFtAAAAA3NpZ20AAAACdjE=	key=dGVybS9ub3JtYWxpemF0aW9ufGN0eDAoZGF0YSBJbnQgKCkgKCkpfHR5cGUodHlwZSAwKXx0ZXJtKGRhdGEgRXF1aXZhbGVudCAoKGRhdGEgSW50ICgpICgpKSkgKChhcHAgKGFwcCAoZ2xvYmFsIGludF9tdWwpICh2YXIgMCkpIChpbnQgNykpIChhcHAgKGFwcCAoZ2xvYmFsIGludF9tdWwpICh2YXIgMCkpIChpbnQgNykpKSkjMTM0	pieces=ctx0::(data Int () ());;type::(type 0);;term::(data Equivalent ((data Int () ())) ((app (app (global int_mul) (var 0)) (int 7)) (app (app (global int_mul) (var 0)) (int 7))))
antigen-record	kind=typed_term	assay=term/subject_reduction	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9zdWJqZWN0X3JlZHVjdGlvbnx0eXBlKGZsb2F0LXR5cGUpfHRlcm0oYXBwIChhcHAgKGdsb2JhbCBmbG9hdF9zdWIpIChmbG9hdCAtMi43NSkpIChmbG9hdCAxLjUpKSMxMzU=	pieces=type::(float-type);;term::(app (app (global float_sub) (float -2.75)) (float 1.5))
antigen-record	kind=typed_term	assay=term/subject_reduction	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9zdWJqZWN0X3JlZHVjdGlvbnx0eXBlKGRhdGEgQm9vbCAoKSAoKSl8dGVybShhcHAgKGFwcCAoZ2xvYmFsIGludF9sdCkgKGFwcCAoYXBwIChnbG9iYWwgaW50X3JlbSkgKGludCAtNykpIChpbnQgMCkpKSAoaW50IDkpKSMxMzY=	pieces=type::(data Bool () ());;term::(app (app (global int_lt) (app (app (global int_rem) (int -7)) (int 0))) (int 9))
antigen-record	kind=typed_term	assay=term/subject_reduction	label=well_typed	seed=-	note=propositional equality (inductive Equivalent)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9zdWJqZWN0X3JlZHVjdGlvbnx0eXBlKGRhdGEgRXF1aXZhbGVudCAoKGRhdGEgQmQgKCkgKCkpKSAoKGN0b3IgVCkgKGN0b3IgVCkpKXx0ZXJtKGFwcCAobGFtIHVucmVzdHJpY3RlZCAoZGF0YSBFcXVpdmFsZW50ICgoZGF0YSBCZCAoKSAoKSkpICgoY3RvciBUKSAoY3RvciBUKSkpICh2YXIgMCkpIChjdG9yIHJlZmxleGl2ZSAoZGF0YSBCZCAoKSAoKSkgKGN0b3IgVCkpKSMxMzc=	pieces=type::(data Equivalent ((data Bd () ())) ((ctor T) (ctor T)));;term::(app (lam unrestricted (data Equivalent ((data Bd () ())) ((ctor T) (ctor T))) (var 0)) (ctor reflexive (data Bd () ()) (ctor T)))
antigen-record	kind=typed_term	assay=term/subject_reduction	label=well_typed	seed=-	note=dependent match (indexed Vec case)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQFtAAAAA3NpZ20AAAACdjE=	key=dGVybS9zdWJqZWN0X3JlZHVjdGlvbnxjdHgwKGRhdGEgVHkgKCkgKChwaSB1bnJlc3RyaWN0ZWQgKGRhdGEgTmF0ICgpICgpKSAoZGF0YSBOYXQgKCkgKCkpKSkpfHR5cGUoZGF0YSBOYXQgKCkgKCkpfHRlcm0oY2FzZSAodmFyIDApIChsYW0gdW5yZXN0cmljdGVkICh0eXBlIDApIChsYW0gdW5yZXN0cmljdGVkIChkYXRhIFR5ICgpICgodmFyIDApKSkgKGRhdGEgTmF0ICgpICgpKSkpIChicmFuY2ggdG5hdCAwIChjdG9yIFopKSAoYnJhbmNoIHRiZCAwIChjdG9yIFopKSAoYnJhbmNoIHRpbnQgMCAoY3RvciBaKSkgKGJyYW5jaCB0Zmx0IDAgKGN0b3IgWikpIChicmFuY2ggdHBpIDAgKGN0b3IgWikpIChicmFuY2ggdHNpZyAwIChjdG9yIFopKSAoYnJhbmNoIHR2ZWMgMCAoY3RvciBaKSkpIzEzOA==	pieces=ctx0::(data Ty () ((pi unrestricted (data Nat () ()) (data Nat () ()))));;type::(data Nat () ());;term::(case (var 0) (lam unrestricted (type 0) (lam unrestricted (data Ty () ((var 0))) (data Nat () ()))) (branch tnat 0 (ctor Z)) (branch tbd 0 (ctor Z)) (branch tint 0 (ctor Z)) (branch tflt 0 (ctor Z)) (branch tpi 0 (ctor Z)) (branch tsig 0 (ctor Z)) (branch tvec 0 (ctor Z)))
antigen-record	kind=typed_term	assay=term/normalization	label=well_typed	seed=-	note=propositional equality (inductive Equivalent)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9ub3JtYWxpemF0aW9ufHR5cGUoZGF0YSBOYXQgKCkgKCkpfHRlcm0oYXBwIChjYXNlIChjdG9yIHJlZmxleGl2ZSAoZmxvYXQtdHlwZSkgKGZsb2F0IC0zLjUpKSAobGFtIHVucmVzdHJpY3RlZCAoZmxvYXQtdHlwZSkgKGxhbSB1bnJlc3RyaWN0ZWQgKGZsb2F0LXR5cGUpIChsYW0gdW5yZXN0cmljdGVkIChkYXRhIEVxdWl2YWxlbnQgKChmbG9hdC10eXBlKSkgKCh2YXIgMSkgKHZhciAwKSkpIChwaSB1bnJlc3RyaWN0ZWQgKGFwcCAobGFtIHVucmVzdHJpY3RlZCAoZmxvYXQtdHlwZSkgKGRhdGEgTmF0ICgpICgpKSkgKHZhciAyKSkgKGFwcCAobGFtIHVucmVzdHJpY3RlZCAoZmxvYXQtdHlwZSkgKGRhdGEgTmF0ICgpICgpKSkgKHZhciAyKSkpKSkpIChicmFuY2ggcmVmbGV4aXZlIDEgKGxhbSB1bnJlc3RyaWN0ZWQgKGFwcCAobGFtIHVucmVzdHJpY3RlZCAoZmxvYXQtdHlwZSkgKGRhdGEgTmF0ICgpICgpKSkgKGZsb2F0IC0zLjUpKSAodmFyIDApKSkpIChjdG9yIFopKSMxMzk=	pieces=type::(data Nat () ());;term::(app (case (ctor reflexive (float-type) (float -3.5)) (lam unrestricted (float-type) (lam unrestricted (float-type) (lam unrestricted (data Equivalent ((float-type)) ((var 1) (var 0))) (pi unrestricted (app (lam unrestricted (float-type) (data Nat () ())) (var 2)) (app (lam unrestricted (float-type) (data Nat () ())) (var 2)))))) (branch reflexive 1 (lam unrestricted (app (lam unrestricted (float-type) (data Nat () ())) (float -3.5)) (var 0)))) (ctor Z))
antigen-record	kind=typed_term	assay=term/normalization	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9ub3JtYWxpemF0aW9ufHR5cGUoZmxvYXQtdHlwZSl8dGVybShhcHAgKGFwcCAoZ2xvYmFsIGZsb2F0X2RpdikgKGZsb2F0IC01LjApKSAoYXBwIChhcHAgKGdsb2JhbCBmbG9hdF9zdWIpIChmbG9hdCAyLjUpKSAoZmxvYXQgLTEuMjUpKSkjMTQw	pieces=type::(float-type);;term::(app (app (global float_div) (float -5.0)) (app (app (global float_sub) (float 2.5)) (float -1.25)))
antigen-record	kind=typed_term	assay=term/normalization	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9ub3JtYWxpemF0aW9ufHR5cGUoZGF0YSBCb29sICgpICgpKXx0ZXJtKGFwcCAoYXBwIChnbG9iYWwgaW50X2d0KSAoYXBwIChhcHAgKGdsb2JhbCBpbnRfc3ViKSAoaW50IDE3KSkgKGludCA3KSkpIChhcHAgKGFwcCAoZ2xvYmFsIGludF9hZGQpIChpbnQgMikpIChpbnQgMTcpKSkjMTQx	pieces=type::(data Bool () ());;term::(app (app (global int_gt) (app (app (global int_sub) (int 17)) (int 7))) (app (app (global int_add) (int 2)) (int 17)))
antigen-record	kind=typed_term	assay=term/normalization	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9ub3JtYWxpemF0aW9ufHR5cGUoZGF0YSBCb29sICgpICgpKXx0ZXJtKGFwcCAoYXBwIChnbG9iYWwgZmxvYXRfZ3QpIChmbG9hdCA0LjI1KSkgKGZsb2F0IDAuNzUpKSMxNDI=	pieces=type::(data Bool () ());;term::(app (app (global float_gt) (float 4.25)) (float 0.75))
antigen-record	kind=typed_term	assay=term/normalization	label=well_typed	seed=-	note=dependent match (indexed Vec case)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQJtAAAAA3NpZ20AAAACdjE=	key=dGVybS9ub3JtYWxpemF0aW9ufGN0eDAoZGF0YSBWZWMgKCkgKCh2YXIgMCkpKXxjdHgxKGRhdGEgTmF0ICgpICgpKXx0eXBlKGZsb2F0LXR5cGUpfHRlcm0oY2FzZSAodmFyIDApIChsYW0gdW5yZXN0cmljdGVkIChkYXRhIE5hdCAoKSAoKSkgKGxhbSB1bnJlc3RyaWN0ZWQgKGRhdGEgVmVjICgpICgodmFyIDApKSkgKGZsb2F0LXR5cGUpKSkgKGJyYW5jaCB2bmlsIDAgKGZsb2F0IC00LjUpKSAoYnJhbmNoIHZjb25zIDMgKGZsb2F0IDIuNSkpKSMxNDM=	pieces=ctx0::(data Vec () ((var 0)));;ctx1::(data Nat () ());;type::(float-type);;term::(case (var 0) (lam unrestricted (data Nat () ()) (lam unrestricted (data Vec () ((var 0))) (float-type))) (branch vnil 0 (float -4.5)) (branch vcons 3 (float 2.5)))
antigen-record	kind=typed_term	assay=term/subject_reduction	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9zdWJqZWN0X3JlZHVjdGlvbnx0eXBlKGRhdGEgQm9vbCAoKSAoKSl8dGVybShhcHAgKGFwcCAoYXBwIChnbG9iYWwgc3RydWN0X2VxKSAoZmxvYXQtdHlwZSkpIChmbG9hdCAxLjc1KSkgKGZsb2F0IDIuMjUpKSMxNDQ=	pieces=type::(data Bool () ());;term::(app (app (app (global struct_eq) (float-type)) (float 1.75)) (float 2.25))
antigen-record	kind=typed_term	assay=term/normalization	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9ub3JtYWxpemF0aW9ufHR5cGUoZGF0YSBCb29sICgpICgpKXx0ZXJtKGFwcCAoYXBwIChnbG9iYWwgZmxvYXRfZXEpIChhcHAgKGFwcCAoZ2xvYmFsIGZsb2F0X2FkZCkgKGZsb2F0IC0wLjUpKSAoZmxvYXQgLTIuMCkpKSAoZmxvYXQgLTMuMCkpIzE0NQ==	pieces=type::(data Bool () ());;term::(app (app (global float_eq) (app (app (global float_add) (float -0.5)) (float -2.0))) (float -3.0))
antigen-record	kind=malformed	assay=term/rejection	label=ill_typed	seed=-	note=malformed (must reject): case motive returns a non-type var	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9yZWplY3Rpb258dGVybShjYXNlIChjdG9yIFopIChsYW0gdW5yZXN0cmljdGVkIChkYXRhIE5hdCAoKSAoKSkgKHZhciAwKSkgKGJyYW5jaCBaIDAgKGN0b3IgWikpIChicmFuY2ggUyAxIChjdG9yIFopKSkjMTQ2	pieces=term::(case (ctor Z) (lam unrestricted (data Nat () ()) (var 0)) (branch Z 0 (ctor Z)) (branch S 1 (ctor Z)))
antigen-record	kind=typed_term	assay=term/subject_reduction	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9zdWJqZWN0X3JlZHVjdGlvbnx0eXBlKGRhdGEgQm9vbCAoKSAoKSl8dGVybShhcHAgKGFwcCAoZ2xvYmFsIGludF9nZSkgKGludCAyKSkgKGludCAtMjApKSMxNDc=	pieces=type::(data Bool () ());;term::(app (app (global int_ge) (int 2)) (int -20))
antigen-record	kind=typed_term	assay=term/subject_reduction	label=well_typed	seed=-	note=propositional equality (inductive Equivalent)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9zdWJqZWN0X3JlZHVjdGlvbnx0eXBlKGRhdGEgRXF1aXZhbGVudCAoKGZsb2F0LXR5cGUpKSAoKGZsb2F0IDAuNSkgKGZsb2F0IDAuNSkpKXx0ZXJtKGN0b3IgcmVmbGV4aXZlIChmbG9hdC10eXBlKSAoZmxvYXQgMC41KSkjMTQ4	pieces=type::(data Equivalent ((float-type)) ((float 0.5) (float 0.5)));;term::(ctor reflexive (float-type) (float 0.5))
antigen-record	kind=typed_term	assay=term/subject_reduction	label=well_typed	seed=-	note=dependent match (indexed Vec case)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQFtAAAAA3NpZ20AAAACdjE=	key=dGVybS9zdWJqZWN0X3JlZHVjdGlvbnxjdHgwKGRhdGEgVGdmICgpICgoZmxvYXQgMC4wKSkpfHR5cGUoZGF0YSBOYXQgKCkgKCkpfHRlcm0oY2FzZSAodmFyIDApIChsYW0gdW5yZXN0cmljdGVkIChmbG9hdC10eXBlKSAobGFtIHVucmVzdHJpY3RlZCAoZGF0YSBUZ2YgKCkgKCh2YXIgMCkpKSAoZGF0YSBOYXQgKCkgKCkpKSkgKGJyYW5jaCB0Z2YwIDAgKGN0b3IgWikpIChicmFuY2ggdGdmMSAwIChjdG9yIFopKSkjMTQ5	pieces=ctx0::(data Tgf () ((float 0.0)));;type::(data Nat () ());;term::(case (var 0) (lam unrestricted (float-type) (lam unrestricted (data Tgf () ((var 0))) (data Nat () ()))) (branch tgf0 0 (ctor Z)) (branch tgf1 0 (ctor Z)))
antigen-record	kind=typed_term	assay=term/normalization	label=well_typed	seed=-	note=dependent match (indexed Vec case)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9ub3JtYWxpemF0aW9ufHR5cGUoZGF0YSBOYXQgKCkgKCkpfHRlcm0oY2FzZSAobmF0IDApIChsYW0gdW5yZXN0cmljdGVkIChkYXRhIE5hdCAoKSAoKSkgKGRhdGEgTmF0ICgpICgpKSkgKGJyYW5jaCBaIDAgKGN0b3IgWikpIChicmFuY2ggUyAxICh2YXIgMCkpKSMxNTA=	pieces=type::(data Nat () ());;term::(case (nat 0) (lam unrestricted (data Nat () ()) (data Nat () ())) (branch Z 0 (ctor Z)) (branch S 1 (var 0)))
antigen-record	kind=typed_term	assay=term/normalization	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9ub3JtYWxpemF0aW9ufHR5cGUoZGF0YSBJbnQgKCkgKCkpfHRlcm0oYXBwIChhcHAgKGdsb2JhbCBpbnRfbXVsKSAoaW50IC0xMSkpIChhcHAgKGFwcCAoZ2xvYmFsIGludF9yZW0pIChpbnQgMTgpKSAoaW50IDE0KSkpIzE1MQ==	pieces=type::(data Int () ());;term::(app (app (global int_mul) (int -11)) (app (app (global int_rem) (int 18)) (int 14)))
antigen-record	kind=typed_term	assay=term/normalization	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9ub3JtYWxpemF0aW9ufHR5cGUoZGF0YSBJbnQgKCkgKCkpfHRlcm0oYXBwIChhcHAgKGdsb2JhbCBpbnRfZGl2KSAoaW50IC0yKSkgKGFwcCAoYXBwIChnbG9iYWwgaW50X3N1YikgKGFwcCAoYXBwIChnbG9iYWwgaW50X2FkZCkgKGludCAtMjApKSAoaW50IC0xMCkpKSAoYXBwIChhcHAgKGdsb2JhbCBpbnRfYWRkKSAoaW50IDE4KSkgKGludCAxNikpKSkjMTUy	pieces=type::(data Int () ());;term::(app (app (global int_div) (int -2)) (app (app (global int_sub) (app (app (global int_add) (int -20)) (int -10))) (app (app (global int_add) (int 18)) (int 16))))
antigen-record	kind=typed_term	assay=term/normalization	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9ub3JtYWxpemF0aW9ufHR5cGUoZGF0YSBCb29sICgpICgpKXx0ZXJtKGFwcCAoYXBwIChnbG9iYWwgaW50X2xlKSAoaW50IC0xMSkpIChpbnQgNSkpIzE1Mw==	pieces=type::(data Bool () ());;term::(app (app (global int_le) (int -11)) (int 5))
antigen-record	kind=typed_term	assay=term/normalization	label=well_typed	seed=-	note=dependent match (indexed Vec case)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQFtAAAAA3NpZ20AAAACdjE=	key=dGVybS9ub3JtYWxpemF0aW9ufGN0eDAoZGF0YSBUeSAoKSAoKGRhdGEgVmVjICgoY3RvciBTIChjdG9yIFopKSkgKCkpKSl8dHlwZShkYXRhIE5hdCAoKSAoKSl8dGVybShjYXNlICh2YXIgMCkgKGxhbSB1bnJlc3RyaWN0ZWQgKHR5cGUgMCkgKGxhbSB1bnJlc3RyaWN0ZWQgKGRhdGEgVHkgKCkgKCh2YXIgMCkpKSAoZGF0YSBOYXQgKCkgKCkpKSkgKGJyYW5jaCB0bmF0IDAgKGN0b3IgUyAoY3RvciBTIChjdG9yIFMgKGN0b3IgUyAoY3RvciBaKSkpKSkpIChicmFuY2ggdGJkIDAgKGN0b3IgWikpIChicmFuY2ggdGludCAwIChjdG9yIFopKSAoYnJhbmNoIHRmbHQgMCAoY3RvciBaKSkgKGJyYW5jaCB0cGkgMCAoY3RvciBaKSkgKGJyYW5jaCB0c2lnIDAgKGN0b3IgWikpIChicmFuY2ggdHZlYyAwIChjdG9yIFopKSkjMTU0	pieces=ctx0::(data Ty () ((data Vec ((ctor S (ctor Z))) ())));;type::(data Nat () ());;term::(case (var 0) (lam unrestricted (type 0) (lam unrestricted (data Ty () ((var 0))) (data Nat () ()))) (branch tnat 0 (ctor S (ctor S (ctor S (ctor S (ctor Z)))))) (branch tbd 0 (ctor Z)) (branch tint 0 (ctor Z)) (branch tflt 0 (ctor Z)) (branch tpi 0 (ctor Z)) (branch tsig 0 (ctor Z)) (branch tvec 0 (ctor Z)))
antigen-record	kind=typed_term	assay=term/subject_reduction	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9zdWJqZWN0X3JlZHVjdGlvbnx0eXBlKGRhdGEgQm9vbCAoKSAoKSl8dGVybShhcHAgKGFwcCAoZ2xvYmFsIGZsb2F0X2xlKSAoZmxvYXQgLTIuNSkpIChmbG9hdCAxLjUpKSMxNTU=	pieces=type::(data Bool () ());;term::(app (app (global float_le) (float -2.5)) (float 1.5))
antigen-record	kind=typed_term	assay=term/subject_reduction	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9zdWJqZWN0X3JlZHVjdGlvbnx0eXBlKGRhdGEgQm9vbCAoKSAoKSl8dGVybShhcHAgKGFwcCAoZ2xvYmFsIGludF9sdCkgKGludCAxMykpIChpbnQgLTIpKSMxNTY=	pieces=type::(data Bool () ());;term::(app (app (global int_lt) (int 13)) (int -2))
antigen-record	kind=typed_term	assay=term/normalization	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9ub3JtYWxpemF0aW9ufHR5cGUoZGF0YSBCb29sICgpICgpKXx0ZXJtKGFwcCAoYXBwIChhcHAgKGdsb2JhbCBzdHJ1Y3RfbmUpIChmbG9hdC10eXBlKSkgKGZsb2F0IDQuNzUpKSAoZmxvYXQgLTQuNSkpIzE1Nw==	pieces=type::(data Bool () ());;term::(app (app (app (global struct_ne) (float-type)) (float 4.75)) (float -4.5))
antigen-record	kind=typed_term	assay=term/subject_reduction	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9zdWJqZWN0X3JlZHVjdGlvbnx0eXBlKGRhdGEgSW50ICgpICgpKXx0ZXJtKGFwcCAoZ2xvYmFsIGludF9uZWcpIChpbnQgLTE5KSkjMTU4	pieces=type::(data Int () ());;term::(app (global int_neg) (int -19))
antigen-record	kind=typed_term	assay=term/normalization	label=well_typed	seed=-	note=dependent match (indexed Vec case)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQJtAAAAA3NpZ20AAAACdjE=	key=dGVybS9ub3JtYWxpemF0aW9ufGN0eDAoZGF0YSBUeSAoKSAoKHZhciAwKSkpfGN0eDEodHlwZSAwKXx0eXBlKGRhdGEgTmF0ICgpICgpKXx0ZXJtKGNhc2UgKHZhciAwKSAobGFtIHVucmVzdHJpY3RlZCAodHlwZSAwKSAobGFtIHVucmVzdHJpY3RlZCAoZGF0YSBUeSAoKSAoKHZhciAwKSkpIChkYXRhIE5hdCAoKSAoKSkpKSAoYnJhbmNoIHRuYXQgMCAoY3RvciBTIChjdG9yIFMgKGN0b3IgUyAoY3RvciBaKSkpKSkgKGJyYW5jaCB0YmQgMCAoY3RvciBaKSkgKGJyYW5jaCB0aW50IDAgKGN0b3IgWikpIChicmFuY2ggdGZsdCAwIChjdG9yIFopKSAoYnJhbmNoIHRwaSAwIChjdG9yIFopKSAoYnJhbmNoIHRzaWcgMCAoY3RvciBaKSkgKGJyYW5jaCB0dmVjIDAgKGN0b3IgWikpKSMxNTk=	pieces=ctx0::(data Ty () ((var 0)));;ctx1::(type 0);;type::(data Nat () ());;term::(case (var 0) (lam unrestricted (type 0) (lam unrestricted (data Ty () ((var 0))) (data Nat () ()))) (branch tnat 0 (ctor S (ctor S (ctor S (ctor Z))))) (branch tbd 0 (ctor Z)) (branch tint 0 (ctor Z)) (branch tflt 0 (ctor Z)) (branch tpi 0 (ctor Z)) (branch tsig 0 (ctor Z)) (branch tvec 0 (ctor Z)))
antigen-record	kind=typed_term	assay=term/subject_reduction	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9zdWJqZWN0X3JlZHVjdGlvbnx0eXBlKGZsb2F0LXR5cGUpfHRlcm0oYXBwIChnbG9iYWwgZmxvYXRfbmVnKSAoYXBwIChhcHAgKGdsb2JhbCBmbG9hdF9zdWIpIChmbG9hdCA0LjI1KSkgKGZsb2F0IC0yLjUpKSkjMTYw	pieces=type::(float-type);;term::(app (global float_neg) (app (app (global float_sub) (float 4.25)) (float -2.5)))
antigen-record	kind=typed_term	assay=term/subject_reduction	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9zdWJqZWN0X3JlZHVjdGlvbnx0eXBlKGZsb2F0LXR5cGUpfHRlcm0oYXBwIChhcHAgKGdsb2JhbCBmbG9hdF9kaXYpIChmbG9hdCAtNC41KSkgKGZsb2F0IDAuMCkpIzE2MQ==	pieces=type::(float-type);;term::(app (app (global float_div) (float -4.5)) (float 0.0))
antigen-record	kind=typed_term	assay=term/normalization	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9ub3JtYWxpemF0aW9ufHR5cGUoZGF0YSBCb29sICgpICgpKXx0ZXJtKGFwcCAoYXBwIChnbG9iYWwgZmxvYXRfZ2UpIChmbG9hdCAtMS43NSkpIChmbG9hdCAzLjI1KSkjMTYy	pieces=type::(data Bool () ());;term::(app (app (global float_ge) (float -1.75)) (float 3.25))
antigen-record	kind=typed_term	assay=term/normalization	label=well_typed	seed=-	note=dependent match (indexed Vec case)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQFtAAAAA3NpZ20AAAACdjE=	key=dGVybS9ub3JtYWxpemF0aW9ufGN0eDAoZGF0YSBUeSAoKSAoKGRhdGEgQmQgKCkgKCkpKSl8dHlwZShkYXRhIE5hdCAoKSAoKSl8dGVybShjYXNlICh2YXIgMCkgKGxhbSB1bnJlc3RyaWN0ZWQgKHR5cGUgMCkgKGxhbSB1bnJlc3RyaWN0ZWQgKGRhdGEgVHkgKCkgKCh2YXIgMCkpKSAoZGF0YSBOYXQgKCkgKCkpKSkgKGJyYW5jaCB0bmF0IDAgKGN0b3IgUyAoY3RvciBaKSkpIChicmFuY2ggdGJkIDAgKGN0b3IgWikpIChicmFuY2ggdGludCAwIChjdG9yIFopKSAoYnJhbmNoIHRmbHQgMCAoY3RvciBaKSkgKGJyYW5jaCB0cGkgMCAoY3RvciBaKSkgKGJyYW5jaCB0c2lnIDAgKGN0b3IgWikpIChicmFuY2ggdHZlYyAwIChjdG9yIFopKSkjMTYz	pieces=ctx0::(data Ty () ((data Bd () ())));;type::(data Nat () ());;term::(case (var 0) (lam unrestricted (type 0) (lam unrestricted (data Ty () ((var 0))) (data Nat () ()))) (branch tnat 0 (ctor S (ctor Z))) (branch tbd 0 (ctor Z)) (branch tint 0 (ctor Z)) (branch tflt 0 (ctor Z)) (branch tpi 0 (ctor Z)) (branch tsig 0 (ctor Z)) (branch tvec 0 (ctor Z)))
antigen-record	kind=typed_term	assay=term/subject_reduction	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9zdWJqZWN0X3JlZHVjdGlvbnx0eXBlKGRhdGEgQm9vbCAoKSAoKSl8dGVybShhcHAgKGFwcCAoZ2xvYmFsIGZsb2F0X2x0KSAoZmxvYXQgLTUuMCkpIChmbG9hdCAyLjc1KSkjMTY0	pieces=type::(data Bool () ());;term::(app (app (global float_lt) (float -5.0)) (float 2.75))
antigen-record	kind=typed_term	assay=term/subject_reduction	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9zdWJqZWN0X3JlZHVjdGlvbnx0eXBlKGRhdGEgQm9vbCAoKSAoKSl8dGVybShhcHAgKGFwcCAoZ2xvYmFsIGludF9nZSkgKGFwcCAoYXBwIChnbG9iYWwgaW50X2RpdikgKGludCAtMykpIChhcHAgKGFwcCAoZ2xvYmFsIGludF9kaXYpIChpbnQgLTE4KSkgKGludCAtMTkpKSkpIChpbnQgMTUpKSMxNjU=	pieces=type::(data Bool () ());;term::(app (app (global int_ge) (app (app (global int_div) (int -3)) (app (app (global int_div) (int -18)) (int -19)))) (int 15))
antigen-record	kind=typed_term	assay=term/subject_reduction	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9zdWJqZWN0X3JlZHVjdGlvbnx0eXBlKGZsb2F0LXR5cGUpfHRlcm0oYXBwIChhcHAgKGdsb2JhbCBmbG9hdF9hZGQpIChhcHAgKGFwcCAoZ2xvYmFsIGZsb2F0X2FkZCkgKGFwcCAoYXBwIChnbG9iYWwgZmxvYXRfbXVsKSAoZmxvYXQgNC43NSkpIChmbG9hdCAtMi43NSkpKSAoYXBwIChhcHAgKGdsb2JhbCBmbG9hdF9kaXYpIChmbG9hdCAtMC41KSkgKGZsb2F0IC0yLjApKSkpIChmbG9hdCAtMC4yNSkpIzE2Ng==	pieces=type::(float-type);;term::(app (app (global float_add) (app (app (global float_add) (app (app (global float_mul) (float 4.75)) (float -2.75))) (app (app (global float_div) (float -0.5)) (float -2.0)))) (float -0.25))
