defmodule Cure.ExportTypes.Protobuf do
  @moduledoc """
  Proto3 emitter for `Cure.ExportTypes` (v0.32.0).

  Converts Cure type definitions to valid `proto3` source. Field names
  are converted from `camelCase` to `snake_case`. Field numbers are
  assigned in declaration order, starting at 1.

  ## Type mapping

  | Cure type           | Proto3                                          |
  |---------------------|-------------------------------------------------|
  | `Int`               | `int64`                                         |
  | `Float`             | `double`                                        |
  | `Bool`              | `bool`                                          |
  | `String`            | `string`                                        |
  | `Bytes`             | `bytes`                                         |
  | `List(T)`           | `repeated <T>`                                  |
  | `Option(T)`         | `optional <T>`                                  |
  | `Result(T, E)`      | wrapper message with `oneof result { T ok; E err; }` |
  | `rec Foo { ... }`   | `message Foo { ... }`                           |
  | Pure-enum ADT       | `enum Foo { FOO_UNSPECIFIED = 0; A = 1; ... }`  |
  | Payload-bearing ADT | wrapper `message` + `oneof value { ... }`       |
  | Dependent types     | comment + E068 warning                          |
  """

  @doc """
  Emit a proto3 source string from a list of `Cure.ExportTypes` type defs.

  ## Options

    * `:source_file` -- path to the source `.cure` file, used in the
      generated file header comment.
  """
  @spec emit([map()], keyword()) :: String.t()
  def emit(type_defs, opts \\ []) do
    source_file = Keyword.get(opts, :source_file, "unknown")

    header = """
    // Generated by `cure export-types --target protobuf` from #{source_file}
    // Do not edit by hand.
    syntax = "proto3";

    """

    body =
      type_defs
      |> Enum.map(&emit_def/1)
      |> Enum.reject(&(&1 == ""))
      |> Enum.join("\n")

    header <> body
  end

  # -- Top-level dispatcher -----------------------------------------------------

  defp emit_def(%{kind: :record, name: name, doc: doc, fields: fields}) do
    doc_comment = maybe_doc_comment(doc)
    field_lines = emit_record_fields(fields, 1)
    "#{doc_comment}message #{name} {\n#{field_lines}}\n"
  end

  defp emit_def(%{kind: :enum, name: name, doc: doc, variants: variants}) do
    if pure_enum?(variants) do
      emit_proto_enum(name, doc, variants)
    else
      emit_oneof_message(name, doc, variants)
    end
  end

  defp emit_def(%{kind: :alias}) do
    # Type aliases are not directly representable in proto3 without
    # a concrete struct. Skip silently.
    ""
  end

  defp emit_def(_), do: ""

  # -- Record / message ---------------------------------------------------------

  defp emit_record_fields(fields, _start_n) when fields == [], do: ""

  defp emit_record_fields(fields, start_n) do
    fields
    |> Enum.with_index(start_n)
    |> Enum.map(fn {%{name: fname, type: type_ast}, n} ->
      proto_type = map_type(type_ast)
      snake = to_snake(fname)
      "  #{proto_type} #{snake} = #{n};\n"
    end)
    |> Enum.join()
  end

  # -- Pure enum ----------------------------------------------------------------

  defp pure_enum?(variants) do
    Enum.all?(variants, fn %{payload: p} -> is_nil(p) end)
  end

  defp emit_proto_enum(name, doc, variants) do
    doc_comment = maybe_doc_comment(doc)
    unspecified = "  #{upcase_name(name)}_UNSPECIFIED = 0;\n"

    variant_lines =
      variants
      |> Enum.with_index(1)
      |> Enum.map(fn {%{name: vname}, n} ->
        "  #{upcase_name(vname)} = #{n};\n"
      end)
      |> Enum.join()

    "#{doc_comment}enum #{name} {\n#{unspecified}#{variant_lines}}\n"
  end

  # -- Payload-bearing ADT (oneof message) --------------------------------------

  defp emit_oneof_message(name, doc, variants) do
    doc_comment = maybe_doc_comment(doc)

    # Emit one nested message per payload-bearing variant.
    nested_messages =
      variants
      |> Enum.filter(fn %{payload: p} -> not is_nil(p) end)
      |> Enum.map(fn %{name: vname, payload: payload} ->
        payload_msg_name = "#{name}#{vname}Payload"
        payload_field = emit_payload_message(payload_msg_name, payload)
        {vname, payload_msg_name, payload_field}
      end)

    # Build the oneof block.
    oneof_fields =
      variants
      |> Enum.with_index(1)
      |> Enum.map(fn {%{name: vname, payload: payload}, n} ->
        if is_nil(payload) do
          # Payload-less variant: use google.protobuf.Empty equivalent (bool placeholder).
          "    bool #{to_snake(vname)} = #{n};\n"
        else
          payload_msg_name = "#{name}#{vname}Payload"
          "    #{payload_msg_name} #{to_snake(vname)} = #{n};\n"
        end
      end)
      |> Enum.join()

    nested_bodies =
      nested_messages
      |> Enum.map(fn {_, _, body} -> body end)
      |> Enum.join("\n")

    oneof_block = "  oneof value {\n#{oneof_fields}  }\n"

    "#{doc_comment}message #{name} {\n#{oneof_block}}\n\n#{nested_bodies}"
  end

  defp emit_payload_message(msg_name, {:tuple_payload, types}) do
    fields =
      types
      |> Enum.with_index(1)
      |> Enum.map(fn {type_ast, n} ->
        proto_type = map_type(type_ast)
        "  #{proto_type} field#{n} = #{n};\n"
      end)
      |> Enum.join()

    "message #{msg_name} {\n#{fields}}\n"
  end

  defp emit_payload_message(msg_name, type_ast) do
    proto_type = map_type(type_ast)
    "message #{msg_name} {\n  #{proto_type} value = 1;\n}\n"
  end

  # -- Type mapping -------------------------------------------------------------

  defp map_type(nil), do: "bytes"

  defp map_type({:type, _meta, "Int"}), do: "int64"
  defp map_type({:type, _meta, "Float"}), do: "double"
  defp map_type({:type, _meta, "Bool"}), do: "bool"
  defp map_type({:type, _meta, "String"}), do: "string"
  defp map_type({:type, _meta, "Bytes"}), do: "bytes"
  defp map_type({:type, _meta, "Atom"}), do: "string"
  defp map_type({:type, _meta, "Any"}), do: "bytes"

  defp map_type({:type_app, _meta, "List", [inner]}) do
    "repeated #{map_type(inner)}"
  end

  defp map_type({:type_app, _meta, "Option", [inner]}) do
    "optional #{map_type(inner)}"
  end

  defp map_type({:type_app, _meta, "Result", [ok_type, err_type]}) do
    # Result types become a synthetic wrapper message name. In the
    # context of a field, we output the field type as `bytes` with a
    # comment, since we can't inline a message definition at field level.
    _ok = map_type(ok_type)
    _err = map_type(err_type)
    # Emit a warning for unmappable inline Result types in field position.
    emit_e068_warning("Result(T, E) in field position -- use a named wrapper message instead")
    "bytes /* E068: Result(T, E) -- wrap in a named message */"
  end

  defp map_type({:type, _meta, name}) when is_binary(name) do
    # Assume it's a user-defined message type.
    name
  end

  defp map_type({:dependent, _meta, _}) do
    emit_e068_warning("dependent type has no proto3 equivalent")
    "bytes /* E068: dependent type -- no proto3 equivalent */"
  end

  defp map_type(other) do
    emit_e068_warning("cannot map type #{inspect(other)}")
    "bytes /* E068: unmappable type #{inspect(other)} */"
  end

  defp emit_e068_warning(reason) do
    Cure.Diagnostic.Host.emit_diagnostic(
      Cure.Diagnostic.Operational.export_unmappable(reason),
      output_device: :stderr
    )
  end

  # -- Helpers ------------------------------------------------------------------

  defp maybe_doc_comment(nil), do: ""
  defp maybe_doc_comment(doc) when is_binary(doc), do: "// #{doc}\n"

  defp to_snake(name) when is_binary(name), do: Macro.underscore(name)
  defp to_snake(other), do: to_string(other)

  defp upcase_name(name) when is_binary(name) do
    name
    |> Macro.underscore()
    |> String.upcase()
  end
end
