[project]
name = "cure_calc"
version = "0.1.0"
edition = "2026"

[dependencies]

[compiler]
type_check = false
optimize = false
# stdlib_path = "/path/to/cure/_build/cure/ebin"

[doc]
title = "cure_calc"
main = "Calc"
